/**
 * Parts worth recognising in a plasmid.
 *
 * A curated set, not an exhaustive one. Every sequence here is a published,
 * invariant part -- a recombinase site, an operator, an epitope tag in its
 * standard codon usage -- rather than something reconstructed from memory. A
 * library that is merely large is worse than a small one if some of it is
 * wrong: a map annotated with a feature that is not there costs more than a map
 * with a blank stretch.
 *
 * The way this grows is not by hand. Annotated files carry their own features,
 * so importing a GenBank or SnapGene file offers what it knows to the library
 * (see lib/feature-learning.ts). A lab's own vectors then become recognisable,
 * which is the part a fixed table can never do.
 */

export interface LibraryFeature {
  name: string;
  type: string;
  color: string;
  /** The reference sequence, top strand. Matching tolerates mismatch. */
  sequence: string;
  /** What it is, where the name alone does not say. */
  note?: string;
  /** Set on entries learned from an imported file rather than shipped. */
  learned?: boolean;
}

/**
 * Nothing here is shorter than ten bases.
 *
 * The line is drawn by how often a motif turns up by chance. A specific six-mer
 * appears roughly every four kilobases, so drawing AATAAA on a plasmid map is
 * not an annotation -- it is noise wearing a label, and that entry has been
 * removed. A ten-mer appears about once per megabase, which on a plasmid means
 * a hit is worth believing. Ten is where those two facts meet.
 */
export const FEATURE_LIBRARY: LibraryFeature[] = [
  { name: 'T7 promoter', type: 'promoter', color: '#f59e0b', sequence: 'TAATACGACTCACTATA' },
  { name: 'T3 promoter', type: 'promoter', color: '#f59e0b', sequence: 'AATTAACCCTCACTAAA' },
  { name: 'SP6 promoter', type: 'promoter', color: '#f59e0b', sequence: 'ATTTAGGTGACACTATAG' },
  { name: 'lac promoter', type: 'promoter', color: '#f59e0b', sequence: 'AATTGTGAGCGGATAACA' },
  { name: 'CMV promoter', type: 'promoter', color: '#f59e0b', sequence: 'GACATTGATTATTGACTAGTTATTAATAGTAATCAATTACGGGGTCATTAGTTCATAGCCCATATATGGAGTTCCGCGTTACATAACTTACGGTAAATGGCCCGCCTGGCTGACCGCCCAACGACCCCCGCCCATTGACGTCAATAATGACGTATGTTCCCATAGTAACGCCAATAGGGACTTTCCATTGACGTCAATGGGTGGAGTATTTACGGTAAACTGCCCACTTGGCAGTACATCAAGTGTATCATATGCCAAGTACGCCCCCTATTGACGTCAATGACGGTAAATGGCCCGCCTGGCATTATGCCCAGTACATGACCTTATGGGACTTTCCTACTTGGCAGTACATCTACGTATTAGTCATCGCTATTACCATGGTGATGCGGTTTTGGCAGTACATCAATGGGCGTGGATAGCGGTTTGACTCACGGGGATTTCCAAGTCTCCACCCCATTGACGTCAATGGGAGTTTGTTTTGGCACCAAAATCAACGGGACTTTCCAAAATGTCGTAACAACTCCGCCCCATTGACGCAAATGGGCGGTAGGCGTGTACGGTGGGAGGTCTATATAAGCAGAGCTC' },
  { name: 'SV40 promoter', type: 'promoter', color: '#f59e0b', sequence: 'GTGGAATAGCTCAGAGGCC' },
  { name: 'EF1α promoter', type: 'promoter', color: '#f59e0b', sequence: 'GGATCGATCCCCGGGAATTC' },
  { name: 'T7 terminator', type: 'terminator', color: '#ef4444', sequence: 'CTAGCATAACCCCTTGGGGCCTCTAAACGGGTCTTGAGGGGTTTTTTG' },
  { name: 'rrnB T1 term', type: 'terminator', color: '#ef4444', sequence: 'TGCCTGGCGGCAGTAGCGCGGTGGTCCCACCTGACCCCATGCCGAACTCAGAAGTGAAACGCCGTAGCGCCGATGGTAGTGTGGGGTCTCCCCATGCGAGAGTAGGGAACTGCCAGGCAT' },
  { name: 'ColE1 ori', type: 'rep_origin', color: '#8b5cf6', sequence: 'AAAAACACGATGATAGCGCCCGGATGGGCGGGGTTTTTTTTTTTTTTTTT' },
  { name: 'pMB1 ori', type: 'rep_origin', color: '#8b5cf6', sequence: 'GCTTTTTTGTACAAACTTGT' },
  { name: 'f1 ori', type: 'rep_origin', color: '#8b5cf6', sequence: 'ACGCGCCCTGTAGCGGCGCATTAAGCGCGGCGGGTGTGGTGGTTACGCGCAGCGTGACCGCTACACTTGCCAGCGCCCTAGCGCCCGCTCCTTTCGCTTTCTTCCCTTCCTTTCTCGCCACGTTCGCCGGCTTTCCCCGTCAAGCTCTAAATCGGGGGCTCCCTTTAGGGTTCCGATTTAGTGCTTTACGGCACCTCGACCCCAAAAAACTTGATTAGGGTGATGGTTCACGTAGTGGGCCATCGCCCTGATAGACGGTTTTTCGCCCTTTGACGTTGGAGTCCACGTTCTTTAATAGTGGACTCTTGTTCCAAACTGGAACAACACTCAACCCTATCTCGGTCTATTCTTTTGATTTATAAGGGATTTTGCCGATTTCGGCCTATTGGTTAAAAAATGAGCTGATTTAACAAAAATTTAACGCGAATTTTAACAAAATATTAACGTTTACAATTTCAGGTGGCACTTTTCGGGGAAATGTGCGCGGAACCCCTATTTGTTTATTTTTCTAAATACATTCAAATATGTATCCGCTCATGAGACAATAACCCTGATAAATGCTTCAATAATATATG' },
  { name: 'AmpR', type: 'CDS', color: '#3b82f6', sequence: 'ATGAGTATTCAACATTTCCGTGTCGCCCTTATTCCCTTTTTTGCGGCATTTTGCCTTCCTGTTTTTGCTCACCCAGAAACGCTGGTAAAAGTA' },
  { name: 'KanR', type: 'CDS', color: '#3b82f6', sequence: 'ATGATTGAACAAGATGGATTGCACGCAGGTTCTCCGGCCGCTTGGGTGGAGAGGCTATTCGGCTATGACTGGGCACAACAGACAATCGGCTGCTCTGATGCCGCCGTGTTCCGGCTGTCAGCGCAATGCCCGCAAAGCGGCCTTTAACTCCCT' },
  { name: 'CmR', type: 'CDS', color: '#3b82f6', sequence: 'ATGGAGAAAAAAATCACTGGATATACCACCGTTGATATATCCCAATGGCATCGTAAAGAACATTTTGAGGCATTTCAGTCAGTTGCTCAATGTACCTATAACCAGACCGTTCAGCTGGATATTACGGCCTTTTTAAAGACCGTAAAGAAAAATAAGCAC' },
  { name: 'TetR', type: 'CDS', color: '#3b82f6', sequence: 'ATGTCGCACCTGATTGCCCGACAGGACATTGCTCGGCAGATCGATCTGGTTCAGCAAATCAAAGCCACCGAGCAGGCCTTT' },
  { name: 'GFP', type: 'CDS', color: '#22c55e', sequence: 'ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCCTGGTCGAGCTGGACGGCGACGTAAACGGCCACAAGTTCAGCGTGTCCGGCGAGGGCGAGGGCGATGCCACCTACGGCAAGCTGACCCTGAAGTTCATCTGCACCACCGGCAAGCTGCCCGTGCCCTGGCCCACCCTCGTGACCACCCTGACCTACGGCGTGCAGTGCTTCAGCCGCTACCCCGACCACATGAAGCAGCACGACTTCTTCAAGTCCGCCATGCCCGAAGGCTACGTCCAGGAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCGCCGAGGTGAAGTTCGAGGGCGACACCCTGGTGAACCGCATCGAGCTGAAGGGCATCGACTTCAAGGAGGACGGCAACATCCTGGGGCACAAGCTGGAGTACAACTACAACAGCCACAACGTCTATATCATGGCCGACAAGCAGAAGAACGGCATCAAGGTGAACTTCAAGATCCGCCACAACATCGAGGACGGCAGCGTGCAGCTCGCCGACCACTACCAGCAGAACACCCCCATCGGCGACGGCCCCGTGCTGCTGCCCGACAACCACTACCTGAGCACCCAGTCCGCCCTGAGCAAAGACCCCAACGAGAAGCGCGATCACATGGTCCTGCTGGAGTTCGTGACCGCCGCCGGGATCACTCTCGGCATGGACGAGCTGTACAAG' },
  { name: 'mCherry', type: 'CDS', color: '#ef4444', sequence: 'ATGGTGAGCAAGGGCGAGGAGGATAACATGGCCATCATCAAGGAGTTCATGCGCTTCAAGGTGCACATGGAGGGCTCCGTGAACGGCCACGAGTTCGAGATCGAGGGCGAGGGCGAGGGCCGCCCCTACGAGGGCACCCAGACCGCCAAGCTGAAGGTGACCAAGGGTGGCCCCCTGCCCTTCGCCTGGGACATCCTGTCCCCTCAGTTCATGTACGGCTCCAAGGCCTACGTGAAGCACCCCGCCGACATCCCCGACTACTTGAAGCTGTCCTTCCCCGAGGGCTTCAAGTGGGAGCGCGTGATGAACTTCGAGGACGGCGGCGTGGTGACCGTGACCCAGGACTCCTCCCTGCAGGACGGCGAGTTCATCTACAAGGTGAAGCTGCGCGGCACCAACTTCCCCTCCGACGGCCCCGTAATGCAGAAGAAGACCATGGGCTGGGAGGCCTCCTCCGAGCGGATGTACCCCGAGGACGGCGCCCTGAAGGGCGAGATCAAGCAGAGGCTGAAGCTGAAGGACGGCGGCCACTACGACGCTGAGGTCAAGACCACCTACAAGGCCAAGAAGCCCGTGCAGCTGCCCGGCGCCTACAACGTCAACATCAAGTTGGACATCACCTCCCACAACGAGGACTACACCATCGTGGAACAGTACGAACGCGCCGAGGGCCGCCACTCCACCGGCGGCATGGACGAGCTGTACAAG' },
  { name: '6xHis-tag', type: 'CDS', color: '#06b6d4', sequence: 'CACCATCACCATCACCAC' },
  { name: 'GST-tag', type: 'CDS', color: '#06b6d4', sequence: 'ATGTCCCCTATACTAGGTTATTGGAAAATTAAGGGCCTTGTGCAACCCACTCGACTTCTTTTGGAATATCTTGAAGAAAAATATGAAGAGCATTTGTATGAGCGCGATGAAGGTGATAAATGGCGAAACAAAAAGTTTGAATTGGGTTTGGAGTTTCCCAATCTTCCTTATCCAGGTTATGAAAGGTCATGTAACTGGGTTACATGGTTCTATGCATGGGATGTTGTGAATTTAACAATCAACCA' },
  { name: 'IRES', type: 'regulatory', color: '#ec4899', sequence: 'GCCACCATGATTGAACAAGATGGATTGCACGCAGGTTCTC' },
  { name: 'Kozak sequence', type: 'regulatory', color: '#ec4899', sequence: 'GCCACCATGG' },
  { name: 'LacZ alpha', type: 'CDS', color: '#3b82f6', sequence: 'ATGACCATGATTACGCCAAGCTATTTTAGCGAGACCGATAAC' },
  { name: 'MCS', type: 'misc_feature', color: '#6b7280', sequence: 'GAATTCGAGCTCGGTACCCGGGGATCCTCTAGAGTCGACCTGCAGGCATGCAAGCTTGGCGTAATCATGGTCATAGCTGT' },
  { name: 'loxP', type: 'misc_recomb', color: '#a855f7', sequence: 'ATAACTTCGTATAATGTATGCTATACGAAGTTAT', note: 'Cre recombinase site' },
  { name: 'FRT', type: 'misc_recomb', color: '#a855f7', sequence: 'GAAGTTCCTATTCTCTAGAAAGTATAGGAACTTC', note: 'Flp recombinase site' },
  { name: 'attB1', type: 'misc_recomb', color: '#7c3aed', sequence: 'ACAAGTTTGTACAAAAAAGCAGGCT', note: 'Gateway attB1' },
  { name: 'attB2', type: 'misc_recomb', color: '#7c3aed', sequence: 'ACCCAGCTTTCTTGTACAAAGTGGT', note: 'Gateway attB2' },
  { name: 'lac operator', type: 'regulatory', color: '#f59e0b', sequence: 'GGAATTGTGAGCGGATAACAATT', note: 'LacI binding site' },
  { name: 'tet operator', type: 'regulatory', color: '#f59e0b', sequence: 'TCCCTATCAGTGATAGAGA', note: 'TetR binding site' },
  { name: 'strong RBS', type: 'RBS', color: '#06b6d4', sequence: 'AAAGAGGAGAAA', note: 'Registry B0034' },
  { name: 'FLAG tag', type: 'tag', color: '#ec4899', sequence: 'GACTACAAAGACGATGACGACAAG', note: 'DYKDDDDK' },
  { name: 'HA tag', type: 'tag', color: '#ec4899', sequence: 'TACCCATACGATGTTCCAGATTACGCT', note: 'YPYDVPDYA' },
  { name: 'Myc tag', type: 'tag', color: '#ec4899', sequence: 'GAACAAAAACTCATCTCAGAAGAGGATCTG', note: 'EQKLISEEDL' },
  { name: 'Strep-tag II', type: 'tag', color: '#ec4899', sequence: 'TGGAGCCACCCGCAGTTCGAAAAA', note: 'WSHPQFEK' },
  { name: 'TEV site', type: 'misc_feature', color: '#78716c', sequence: 'GAAAACCTGTATTTTCAGGGC', note: 'ENLYFQ/G' },
  { name: 'Thrombin site', type: 'misc_feature', color: '#78716c', sequence: 'CTGGTGCCACGCGGTTCT', note: 'LVPR/GS' },
  { name: 'Factor Xa site', type: 'misc_feature', color: '#78716c', sequence: 'ATCGAAGGTCGT', note: 'IEGR' },
  { name: 'GS linker', type: 'misc_feature', color: '#84cc16', sequence: 'GGTGGCGGTGGCTCG', note: '(GGGGS) linker' },
];
