// GENERATED FILE -- do not edit by hand.
// Regenerate with: node scripts/build-enzymes.mjs
//
// Source: REBASE version 609, the Restriction Enzyme Database
// (rebase.neb.com), Roberts RJ, Vincze T, Posfai J, Macelis D.
// Filtered to enzymes with at least one commercial supplier, which is what a
// lab can actually use. Type IIB enzymes that cut on both sides of their site
// are omitted, as one cut offset cannot describe them.
import type { Enzyme } from './restrictionEnzymes';

export const REBASE_ENZYMES: Record<string, Enzyme> = {
  "AanI": { name: "AanI", pattern: "TTATAA", cutBefore: 3, cutBottom: 3, overhang: "", overhangType: 'blunt', overhangLength: 0, prototype: "PsiI" },
  "AarI": { name: "AarI", pattern: "CACCTGC", cutBefore: 11, cutBottom: 15, overhang: "", overhangType: '5prime', overhangLength: 4, typeIIS: true },
  "AatII": { name: "AatII", pattern: "GACGTC", cutBefore: 5, cutBottom: 1, overhang: "ACGT", overhangType: '3prime', overhangLength: 4, methylation: "2(6)" },
  "AbsI": { name: "AbsI", pattern: "CCTCGAGG", cutBefore: 2, cutBottom: 6, overhang: "TCGA", overhangType: '5prime', overhangLength: 4 },
  "Acc16I": { name: "Acc16I", pattern: "TGCGCA", cutBefore: 3, cutBottom: 3, overhang: "", overhangType: 'blunt', overhangLength: 0, prototype: "MstI" },
  "Acc36I": { name: "Acc36I", pattern: "ACCTGC", cutBefore: 10, cutBottom: 14, overhang: "", overhangType: '5prime', overhangLength: 4, typeIIS: true, prototype: "BspMI" },
  "Acc65I": { name: "Acc65I", pattern: "GGTACC", cutBefore: 1, cutBottom: 5, overhang: "GTAC", overhangType: '5prime', overhangLength: 4, prototype: "KpnI", methylation: "4(6)" },
  "AccB1I": { name: "AccB1I", pattern: "GGYRCC", cutBefore: 1, cutBottom: 5, overhang: "", overhangType: '5prime', overhangLength: 4, prototype: "HgiCI" },
  "AccB7I": { name: "AccB7I", pattern: "CCANNNNNTGG", cutBefore: 7, cutBottom: 4, overhang: "", overhangType: '3prime', overhangLength: 3, prototype: "PflMI" },
  "AccBSI": { name: "AccBSI", pattern: "CCGCTC", cutBefore: 3, cutBottom: 3, overhang: "", overhangType: 'blunt', overhangLength: 0, typeIIS: true, prototype: "BsrBI" },
  "AccI": { name: "AccI", pattern: "GTMKAC", cutBefore: 2, cutBottom: 4, overhang: "", overhangType: '5prime', overhangLength: 2, methylation: "5(6)" },
  "AccII": { name: "AccII", pattern: "CGCG", cutBefore: 2, cutBottom: 2, overhang: "", overhangType: 'blunt', overhangLength: 0, prototype: "FnuDII", methylation: "1(5)" },
  "AccIII": { name: "AccIII", pattern: "TCCGGA", cutBefore: 1, cutBottom: 5, overhang: "CCGG", overhangType: '5prime', overhangLength: 4, prototype: "BspMII", methylation: "6(6)" },
  "AciI": { name: "AciI", pattern: "CCGC", cutBefore: 1, cutBottom: 3, overhang: "", overhangType: '5prime', overhangLength: 2, typeIIS: true, methylation: "1(5),-2(5)" },
  "AclI": { name: "AclI", pattern: "AACGTT", cutBefore: 2, cutBottom: 4, overhang: "CG", overhangType: '5prime', overhangLength: 2, methylation: "3(5)" },
  "AclWI": { name: "AclWI", pattern: "GGATC", cutBefore: 9, cutBottom: 10, overhang: "", overhangType: '5prime', overhangLength: 1, typeIIS: true, prototype: "BinI" },
  "AcoI": { name: "AcoI", pattern: "YGGCCR", cutBefore: 1, cutBottom: 5, overhang: "GGCC", overhangType: '5prime', overhangLength: 4, prototype: "CfrI" },
  "AcsI": { name: "AcsI", pattern: "RAATTY", cutBefore: 1, cutBottom: 5, overhang: "AATT", overhangType: '5prime', overhangLength: 4, prototype: "ApoI" },
  "AcuI": { name: "AcuI", pattern: "CTGAAG", cutBefore: 22, cutBottom: 20, overhang: "", overhangType: '3prime', overhangLength: 2, typeIIS: true, prototype: "Eco57I", methylation: "?(6)" },
  "AcvI": { name: "AcvI", pattern: "CACGTG", cutBefore: 3, cutBottom: 3, overhang: "", overhangType: 'blunt', overhangLength: 0, prototype: "PmaCI" },
  "AcyI": { name: "AcyI", pattern: "GRCGYC", cutBefore: 2, cutBottom: 4, overhang: "CG", overhangType: '5prime', overhangLength: 2 },
  "AdeI": { name: "AdeI", pattern: "CACNNNGTG", cutBefore: 6, cutBottom: 3, overhang: "", overhangType: '3prime', overhangLength: 3, prototype: "DraIII" },
  "AfeI": { name: "AfeI", pattern: "AGCGCT", cutBefore: 3, cutBottom: 3, overhang: "", overhangType: 'blunt', overhangLength: 0, prototype: "Eco47III" },
  "AfiI": { name: "AfiI", pattern: "CCNNNNNNNGG", cutBefore: 7, cutBottom: 4, overhang: "", overhangType: '3prime', overhangLength: 3, prototype: "BsiYI" },
  "AflII": { name: "AflII", pattern: "CTTAAG", cutBefore: 1, cutBottom: 5, overhang: "TTAA", overhangType: '5prime', overhangLength: 4, methylation: "5(6)" },
  "AflIII": { name: "AflIII", pattern: "ACRYGT", cutBefore: 1, cutBottom: 5, overhang: "", overhangType: '5prime', overhangLength: 4, methylation: "2(4)" },
  "AgeI": { name: "AgeI", pattern: "ACCGGT", cutBefore: 1, cutBottom: 5, overhang: "CCGG", overhangType: '5prime', overhangLength: 4, methylation: "3(5)" },
  "AgsI": { name: "AgsI", pattern: "TTSAA", cutBefore: 3, cutBottom: 2, overhang: "", overhangType: '3prime', overhangLength: 1, methylation: "5(6)" },
  "AhdI": { name: "AhdI", pattern: "GACNNNNNGTC", cutBefore: 6, cutBottom: 5, overhang: "", overhangType: '3prime', overhangLength: 1, prototype: "Eam1105I", methylation: "2(6)" },
  "AhlI": { name: "AhlI", pattern: "ACTAGT", cutBefore: 1, cutBottom: 5, overhang: "CTAG", overhangType: '5prime', overhangLength: 4, prototype: "SpeI" },
  "AjiI": { name: "AjiI", pattern: "CACGTC", cutBefore: 3, cutBottom: 3, overhang: "", overhangType: 'blunt', overhangLength: 0, typeIIS: true, prototype: "BtrI" },
  "AjnI": { name: "AjnI", pattern: "CCWGG", cutBefore: 0, cutBottom: 5, overhang: "", overhangType: '5prime', overhangLength: 5, prototype: "EcoRII", methylation: "1(5)" },
  "AleI": { name: "AleI", pattern: "CACNNNNGTG", cutBefore: 5, cutBottom: 5, overhang: "", overhangType: 'blunt', overhangLength: 0, prototype: "OliI", methylation: "2(6)" },
  "AluBI": { name: "AluBI", pattern: "AGCT", cutBefore: 2, cutBottom: 2, overhang: "", overhangType: 'blunt', overhangLength: 0, prototype: "AluI", methylation: "1(6)" },
  "AluI": { name: "AluI", pattern: "AGCT", cutBefore: 2, cutBottom: 2, overhang: "", overhangType: 'blunt', overhangLength: 0, methylation: "3(5)" },
  "Alw21I": { name: "Alw21I", pattern: "GWGCWC", cutBefore: 5, cutBottom: 1, overhang: "", overhangType: '3prime', overhangLength: 4, prototype: "HgiAI" },
  "Alw26I": { name: "Alw26I", pattern: "GTCTC", cutBefore: 6, cutBottom: 10, overhang: "", overhangType: '5prime', overhangLength: 4, typeIIS: true, prototype: "BsmAI", methylation: "3(5),-4(6)" },
  "Alw44I": { name: "Alw44I", pattern: "GTGCAC", cutBefore: 1, cutBottom: 5, overhang: "TGCA", overhangType: '5prime', overhangLength: 4, prototype: "ApaLI" },
  "AlwI": { name: "AlwI", pattern: "GGATC", cutBefore: 9, cutBottom: 10, overhang: "", overhangType: '5prime', overhangLength: 1, typeIIS: true, prototype: "BinI", methylation: "3(6),-2(6)" },
  "AlwNI": { name: "AlwNI", pattern: "CAGNNNCTG", cutBefore: 6, cutBottom: 3, overhang: "", overhangType: '3prime', overhangLength: 3 },
  "Ama87I": { name: "Ama87I", pattern: "CYCGRG", cutBefore: 1, cutBottom: 5, overhang: "", overhangType: '5prime', overhangLength: 4, prototype: "AvaI" },
  "Aor13HI": { name: "Aor13HI", pattern: "TCCGGA", cutBefore: 1, cutBottom: 5, overhang: "CCGG", overhangType: '5prime', overhangLength: 4, prototype: "BspMII" },
  "AoxI": { name: "AoxI", pattern: "GGCC", cutBefore: 0, cutBottom: 4, overhang: "GGCC", overhangType: '5prime', overhangLength: 4 },
  "ApaI": { name: "ApaI", pattern: "GGGCCC", cutBefore: 5, cutBottom: 1, overhang: "GGCC", overhangType: '3prime', overhangLength: 4, methylation: "4(5)" },
  "ApaLI": { name: "ApaLI", pattern: "GTGCAC", cutBefore: 1, cutBottom: 5, overhang: "TGCA", overhangType: '5prime', overhangLength: 4, methylation: "4(5)" },
  "ApeKI": { name: "ApeKI", pattern: "GCWGC", cutBefore: 1, cutBottom: 4, overhang: "", overhangType: '5prime', overhangLength: 3, prototype: "TseI", methylation: "2(5)" },
  "ApoI": { name: "ApoI", pattern: "RAATTY", cutBefore: 1, cutBottom: 5, overhang: "AATT", overhangType: '5prime', overhangLength: 4, methylation: "3(6)" },
  "AscI": { name: "AscI", pattern: "GGCGCGCC", cutBefore: 2, cutBottom: 6, overhang: "CGCG", overhangType: '5prime', overhangLength: 4, methylation: "?(5)" },
  "AseI": { name: "AseI", pattern: "ATTAAT", cutBefore: 2, cutBottom: 4, overhang: "TA", overhangType: '5prime', overhangLength: 2, prototype: "VspI", methylation: "?(6)" },
  "AsiGI": { name: "AsiGI", pattern: "ACCGGT", cutBefore: 1, cutBottom: 5, overhang: "CCGG", overhangType: '5prime', overhangLength: 4, prototype: "AgeI" },
  "AsiSI": { name: "AsiSI", pattern: "GCGATCGC", cutBefore: 5, cutBottom: 3, overhang: "AT", overhangType: '3prime', overhangLength: 2, prototype: "SgfI", methylation: "2(5)" },
  "AspA2I": { name: "AspA2I", pattern: "CCTAGG", cutBefore: 1, cutBottom: 5, overhang: "CTAG", overhangType: '5prime', overhangLength: 4, prototype: "AvrII" },
  "AspEI": { name: "AspEI", pattern: "GACNNNNNGTC", cutBefore: 6, cutBottom: 5, overhang: "", overhangType: '3prime', overhangLength: 1, prototype: "Eam1105I" },
  "AspLEI": { name: "AspLEI", pattern: "GCGC", cutBefore: 3, cutBottom: 1, overhang: "CG", overhangType: '3prime', overhangLength: 2, prototype: "HhaI" },
  "AspS9I": { name: "AspS9I", pattern: "GGNCC", cutBefore: 1, cutBottom: 4, overhang: "", overhangType: '5prime', overhangLength: 3, prototype: "AsuI", methylation: "4(5)" },
  "AsuC2I": { name: "AsuC2I", pattern: "CCSGG", cutBefore: 2, cutBottom: 3, overhang: "", overhangType: '5prime', overhangLength: 1, prototype: "CauII" },
  "AsuHPI": { name: "AsuHPI", pattern: "GGTGA", cutBefore: 13, cutBottom: 12, overhang: "", overhangType: '3prime', overhangLength: 1, typeIIS: true, prototype: "HphI" },
  "AsuII": { name: "AsuII", pattern: "TTCGAA", cutBefore: 2, cutBottom: 4, overhang: "CG", overhangType: '5prime', overhangLength: 2 },
  "AsuNHI": { name: "AsuNHI", pattern: "GCTAGC", cutBefore: 1, cutBottom: 5, overhang: "CTAG", overhangType: '5prime', overhangLength: 4, prototype: "NheI" },
  "AvaI": { name: "AvaI", pattern: "CYCGRG", cutBefore: 1, cutBottom: 5, overhang: "", overhangType: '5prime', overhangLength: 4, methylation: "1(4)" },
  "AvaII": { name: "AvaII", pattern: "GGWCC", cutBefore: 1, cutBottom: 4, overhang: "", overhangType: '5prime', overhangLength: 3, methylation: "4(5)" },
  "AviII": { name: "AviII", pattern: "TGCGCA", cutBefore: 3, cutBottom: 3, overhang: "", overhangType: 'blunt', overhangLength: 0, prototype: "MstI" },
  "AvrII": { name: "AvrII", pattern: "CCTAGG", cutBefore: 1, cutBottom: 5, overhang: "CTAG", overhangType: '5prime', overhangLength: 4 },
  "AxyI": { name: "AxyI", pattern: "CCTNAGG", cutBefore: 2, cutBottom: 5, overhang: "", overhangType: '5prime', overhangLength: 3, prototype: "SauI" },
  "BaeGI": { name: "BaeGI", pattern: "GKGCMC", cutBefore: 5, cutBottom: 1, overhang: "", overhangType: '3prime', overhangLength: 4, prototype: "BseSI", methylation: "6(5)" },
  "BalI": { name: "BalI", pattern: "TGGCCA", cutBefore: 3, cutBottom: 3, overhang: "", overhangType: 'blunt', overhangLength: 0, methylation: "?(4)" },
  "BamHI": { name: "BamHI", pattern: "GGATCC", cutBefore: 1, cutBottom: 5, overhang: "GATC", overhangType: '5prime', overhangLength: 4, methylation: "5(4)" },
  "BanI": { name: "BanI", pattern: "GGYRCC", cutBefore: 1, cutBottom: 5, overhang: "", overhangType: '5prime', overhangLength: 4, prototype: "HgiCI", methylation: "5(5)" },
  "BanII": { name: "BanII", pattern: "GRGCYC", cutBefore: 5, cutBottom: 1, overhang: "", overhangType: '3prime', overhangLength: 4, prototype: "HgiJII", methylation: "4(5)" },
  "BauI": { name: "BauI", pattern: "CACGAG", cutBefore: 1, cutBottom: 5, overhang: "", overhangType: '5prime', overhangLength: 4, typeIIS: true, prototype: "BsiI" },
  "BbrPI": { name: "BbrPI", pattern: "CACGTG", cutBefore: 3, cutBottom: 3, overhang: "", overhangType: 'blunt', overhangLength: 0, prototype: "PmaCI" },
  "BbsI": { name: "BbsI", pattern: "GAAGAC", cutBefore: 8, cutBottom: 12, overhang: "", overhangType: '5prime', overhangLength: 4, typeIIS: true, prototype: "BbvII" },
  "BbuI": { name: "BbuI", pattern: "GCATGC", cutBefore: 5, cutBottom: 1, overhang: "CATG", overhangType: '3prime', overhangLength: 4, prototype: "SphI" },
  "Bbv12I": { name: "Bbv12I", pattern: "GWGCWC", cutBefore: 5, cutBottom: 1, overhang: "", overhangType: '3prime', overhangLength: 4, prototype: "HgiAI" },
  "BbvCI": { name: "BbvCI", pattern: "CCTCAGC", cutBefore: 2, cutBottom: 5, overhang: "", overhangType: '5prime', overhangLength: 3, typeIIS: true, methylation: "?(5)" },
  "BbvI": { name: "BbvI", pattern: "GCAGC", cutBefore: 13, cutBottom: 17, overhang: "", overhangType: '5prime', overhangLength: 4, typeIIS: true, methylation: "2(5),-2(5)" },
  "BccI": { name: "BccI", pattern: "CCATC", cutBefore: 9, cutBottom: 10, overhang: "", overhangType: '5prime', overhangLength: 1, typeIIS: true, methylation: "3(6)" },
  "BceAI": { name: "BceAI", pattern: "ACGGC", cutBefore: 17, cutBottom: 19, overhang: "", overhangType: '5prime', overhangLength: 2, typeIIS: true, prototype: "BcefI", methylation: "?(4)" },
  "BciVI": { name: "BciVI", pattern: "GTATCC", cutBefore: 12, cutBottom: 11, overhang: "", overhangType: '3prime', overhangLength: 1, typeIIS: true },
  "BclI": { name: "BclI", pattern: "TGATCA", cutBefore: 1, cutBottom: 5, overhang: "GATC", overhangType: '5prime', overhangLength: 4, methylation: "3(6)" },
  "BcnI": { name: "BcnI", pattern: "CCSGG", cutBefore: 2, cutBottom: 3, overhang: "", overhangType: '5prime', overhangLength: 1, prototype: "CauII", methylation: "2(4)" },
  "BcoDI": { name: "BcoDI", pattern: "GTCTC", cutBefore: 6, cutBottom: 10, overhang: "", overhangType: '5prime', overhangLength: 4, typeIIS: true, prototype: "BsmAI", methylation: "?(5)" },
  "BcuI": { name: "BcuI", pattern: "ACTAGT", cutBefore: 1, cutBottom: 5, overhang: "CTAG", overhangType: '5prime', overhangLength: 4, prototype: "SpeI" },
  "BfaI": { name: "BfaI", pattern: "CTAG", cutBefore: 1, cutBottom: 3, overhang: "TA", overhangType: '5prime', overhangLength: 2, prototype: "MaeI" },
  "BfmI": { name: "BfmI", pattern: "CTRYAG", cutBefore: 1, cutBottom: 5, overhang: "", overhangType: '5prime', overhangLength: 4, prototype: "SfeI" },
  "BfuAI": { name: "BfuAI", pattern: "ACCTGC", cutBefore: 10, cutBottom: 14, overhang: "", overhangType: '5prime', overhangLength: 4, typeIIS: true, prototype: "BspMI", methylation: "2(5)" },
  "BfuI": { name: "BfuI", pattern: "GTATCC", cutBefore: 12, cutBottom: 11, overhang: "", overhangType: '3prime', overhangLength: 1, typeIIS: true, prototype: "BciVI" },
  "BglI": { name: "BglI", pattern: "GCCNNNNNGGC", cutBefore: 7, cutBottom: 4, overhang: "", overhangType: '3prime', overhangLength: 3, methylation: "2(4)" },
  "BglII": { name: "BglII", pattern: "AGATCT", cutBefore: 1, cutBottom: 5, overhang: "GATC", overhangType: '5prime', overhangLength: 4, methylation: "5(4)" },
  "BlpI": { name: "BlpI", pattern: "GCTNAGC", cutBefore: 2, cutBottom: 5, overhang: "", overhangType: '5prime', overhangLength: 3, prototype: "EspI", methylation: "?(5)" },
  "BlsI": { name: "BlsI", pattern: "GCNGC", cutBefore: 3, cutBottom: 2, overhang: "", overhangType: '3prime', overhangLength: 1, prototype: "BisI" },
  "BmcAI": { name: "BmcAI", pattern: "AGTACT", cutBefore: 3, cutBottom: 3, overhang: "", overhangType: 'blunt', overhangLength: 0, prototype: "ScaI" },
  "Bme1390I": { name: "Bme1390I", pattern: "CCNGG", cutBefore: 2, cutBottom: 3, overhang: "", overhangType: '5prime', overhangLength: 1, prototype: "ScrFI" },
  "Bme18I": { name: "Bme18I", pattern: "GGWCC", cutBefore: 1, cutBottom: 4, overhang: "", overhangType: '5prime', overhangLength: 3, prototype: "AvaII" },
  "BmeRI": { name: "BmeRI", pattern: "GACNNNNNGTC", cutBefore: 6, cutBottom: 5, overhang: "", overhangType: '3prime', overhangLength: 1, prototype: "Eam1105I" },
  "BmgBI": { name: "BmgBI", pattern: "CACGTC", cutBefore: 3, cutBottom: 3, overhang: "", overhangType: 'blunt', overhangLength: 0, typeIIS: true, prototype: "BtrI" },
  "BmiI": { name: "BmiI", pattern: "GGNNCC", cutBefore: 3, cutBottom: 3, overhang: "", overhangType: 'blunt', overhangLength: 0, prototype: "NlaIV" },
  "BmrFI": { name: "BmrFI", pattern: "CCNGG", cutBefore: 2, cutBottom: 3, overhang: "", overhangType: '5prime', overhangLength: 1, prototype: "ScrFI" },
  "BmrI": { name: "BmrI", pattern: "ACTGGG", cutBefore: 11, cutBottom: 10, overhang: "", overhangType: '3prime', overhangLength: 1, typeIIS: true, prototype: "BfiI", methylation: "?(4)" },
  "BmtI": { name: "BmtI", pattern: "GCTAGC", cutBefore: 5, cutBottom: 1, overhang: "CTAG", overhangType: '3prime', overhangLength: 4, prototype: "NheI", methylation: "2(5)" },
  "BmuI": { name: "BmuI", pattern: "ACTGGG", cutBefore: 11, cutBottom: 10, overhang: "", overhangType: '3prime', overhangLength: 1, typeIIS: true, prototype: "BfiI" },
  "BmyI": { name: "BmyI", pattern: "GDGCHC", cutBefore: 5, cutBottom: 1, overhang: "", overhangType: '3prime', overhangLength: 4, prototype: "SduI" },
  "BoxI": { name: "BoxI", pattern: "GACNNNNGTC", cutBefore: 5, cutBottom: 5, overhang: "", overhangType: 'blunt', overhangLength: 0, prototype: "PshAI" },
  "BpiI": { name: "BpiI", pattern: "GAAGAC", cutBefore: 8, cutBottom: 12, overhang: "", overhangType: '5prime', overhangLength: 4, typeIIS: true, prototype: "BbvII" },
  "BpmI": { name: "BpmI", pattern: "CTGGAG", cutBefore: 22, cutBottom: 20, overhang: "", overhangType: '3prime', overhangLength: 2, typeIIS: true, prototype: "GsuI", methylation: "?(6)" },
  "Bpu10I": { name: "Bpu10I", pattern: "CCTNAGC", cutBefore: 2, cutBottom: 5, overhang: "", overhangType: '5prime', overhangLength: 3, typeIIS: true, methylation: "?(5)" },
  "Bpu1102I": { name: "Bpu1102I", pattern: "GCTNAGC", cutBefore: 2, cutBottom: 5, overhang: "", overhangType: '5prime', overhangLength: 3, prototype: "EspI" },
  "Bpu14I": { name: "Bpu14I", pattern: "TTCGAA", cutBefore: 2, cutBottom: 4, overhang: "CG", overhangType: '5prime', overhangLength: 2, prototype: "AsuII" },
  "BpuEI": { name: "BpuEI", pattern: "CTTGAG", cutBefore: 22, cutBottom: 20, overhang: "", overhangType: '3prime', overhangLength: 2, typeIIS: true, prototype: "Bce83I", methylation: "5(6)" },
  "BpuMI": { name: "BpuMI", pattern: "CCSGG", cutBefore: 2, cutBottom: 3, overhang: "", overhangType: '5prime', overhangLength: 1, prototype: "CauII" },
  "Bsa29I": { name: "Bsa29I", pattern: "ATCGAT", cutBefore: 2, cutBottom: 4, overhang: "CG", overhangType: '5prime', overhangLength: 2, prototype: "ClaI" },
  "BsaAI": { name: "BsaAI", pattern: "YACGTR", cutBefore: 3, cutBottom: 3, overhang: "", overhangType: 'blunt', overhangLength: 0, methylation: "3(5)" },
  "BsaBI": { name: "BsaBI", pattern: "GATNNNNATC", cutBefore: 5, cutBottom: 5, overhang: "", overhangType: 'blunt', overhangLength: 0 },
  "BsaHI": { name: "BsaHI", pattern: "GRCGYC", cutBefore: 2, cutBottom: 4, overhang: "CG", overhangType: '5prime', overhangLength: 2, prototype: "AcyI", methylation: "?(5)" },
  "BsaI": { name: "BsaI", pattern: "GGTCTC", cutBefore: 7, cutBottom: 11, overhang: "", overhangType: '5prime', overhangLength: 4, typeIIS: true, prototype: "Eco31I", methylation: "-4(6)" },
  "BsaJI": { name: "BsaJI", pattern: "CCNNGG", cutBefore: 1, cutBottom: 5, overhang: "", overhangType: '5prime', overhangLength: 4, prototype: "SecI", methylation: "?(4)" },
  "BsaMI": { name: "BsaMI", pattern: "GAATGC", cutBefore: 7, cutBottom: 5, overhang: "", overhangType: '3prime', overhangLength: 2, typeIIS: true, prototype: "BsmI" },
  "BsaWI": { name: "BsaWI", pattern: "WCCGGW", cutBefore: 1, cutBottom: 5, overhang: "CCGG", overhangType: '5prime', overhangLength: 4, prototype: "BetI", methylation: "1(5)" },
  "Bsc4I": { name: "Bsc4I", pattern: "CCNNNNNNNGG", cutBefore: 7, cutBottom: 4, overhang: "", overhangType: '3prime', overhangLength: 3, prototype: "BsiYI", methylation: "2(4)" },
  "Bse118I": { name: "Bse118I", pattern: "RCCGGY", cutBefore: 1, cutBottom: 5, overhang: "CCGG", overhangType: '5prime', overhangLength: 4, prototype: "Cfr10I" },
  "Bse1I": { name: "Bse1I", pattern: "ACTGG", cutBefore: 6, cutBottom: 4, overhang: "", overhangType: '3prime', overhangLength: 2, typeIIS: true, prototype: "BsrI" },
  "Bse21I": { name: "Bse21I", pattern: "CCTNAGG", cutBefore: 2, cutBottom: 5, overhang: "", overhangType: '5prime', overhangLength: 3, prototype: "SauI" },
  "Bse3DI": { name: "Bse3DI", pattern: "GCAATG", cutBefore: 8, cutBottom: 6, overhang: "", overhangType: '3prime', overhangLength: 2, typeIIS: true, prototype: "BsrDI" },
  "Bse8I": { name: "Bse8I", pattern: "GATNNNNATC", cutBefore: 5, cutBottom: 5, overhang: "", overhangType: 'blunt', overhangLength: 0, prototype: "BsaBI" },
  "BseBI": { name: "BseBI", pattern: "CCWGG", cutBefore: 2, cutBottom: 3, overhang: "", overhangType: '5prime', overhangLength: 1, prototype: "EcoRII" },
  "BseDI": { name: "BseDI", pattern: "CCNNGG", cutBefore: 1, cutBottom: 5, overhang: "", overhangType: '5prime', overhangLength: 4, prototype: "SecI" },
  "BseGI": { name: "BseGI", pattern: "GGATG", cutBefore: 7, cutBottom: 5, overhang: "", overhangType: '3prime', overhangLength: 2, typeIIS: true, prototype: "FokI" },
  "BseJI": { name: "BseJI", pattern: "GATNNNNATC", cutBefore: 5, cutBottom: 5, overhang: "", overhangType: 'blunt', overhangLength: 0, prototype: "BsaBI" },
  "BseLI": { name: "BseLI", pattern: "CCNNNNNNNGG", cutBefore: 7, cutBottom: 4, overhang: "", overhangType: '3prime', overhangLength: 3, prototype: "BsiYI" },
  "BseMI": { name: "BseMI", pattern: "GCAATG", cutBefore: 8, cutBottom: 6, overhang: "", overhangType: '3prime', overhangLength: 2, typeIIS: true, prototype: "BsrDI" },
  "BseMII": { name: "BseMII", pattern: "CTCAG", cutBefore: 15, cutBottom: 13, overhang: "", overhangType: '3prime', overhangLength: 2, typeIIS: true, methylation: "4(6)" },
  "BseNI": { name: "BseNI", pattern: "ACTGG", cutBefore: 6, cutBottom: 4, overhang: "", overhangType: '3prime', overhangLength: 2, typeIIS: true, prototype: "BsrI" },
  "BsePI": { name: "BsePI", pattern: "GCGCGC", cutBefore: 1, cutBottom: 5, overhang: "CGCG", overhangType: '5prime', overhangLength: 4 },
  "BseRI": { name: "BseRI", pattern: "GAGGAG", cutBefore: 16, cutBottom: 14, overhang: "", overhangType: '3prime', overhangLength: 2, typeIIS: true, methylation: "5(6),-4(4)" },
  "BseSI": { name: "BseSI", pattern: "GKGCMC", cutBefore: 5, cutBottom: 1, overhang: "", overhangType: '3prime', overhangLength: 4 },
  "BseX3I": { name: "BseX3I", pattern: "CGGCCG", cutBefore: 1, cutBottom: 5, overhang: "GGCC", overhangType: '5prime', overhangLength: 4, prototype: "XmaIII" },
  "BseXI": { name: "BseXI", pattern: "GCAGC", cutBefore: 13, cutBottom: 17, overhang: "", overhangType: '5prime', overhangLength: 4, typeIIS: true, prototype: "BbvI" },
  "BseYI": { name: "BseYI", pattern: "CCCAGC", cutBefore: 1, cutBottom: 5, overhang: "", overhangType: '5prime', overhangLength: 4, typeIIS: true },
  "BsgI": { name: "BsgI", pattern: "GTGCAG", cutBefore: 22, cutBottom: 20, overhang: "", overhangType: '3prime', overhangLength: 2, typeIIS: true, methylation: "?(6)" },
  "Bsh1236I": { name: "Bsh1236I", pattern: "CGCG", cutBefore: 2, cutBottom: 2, overhang: "", overhangType: 'blunt', overhangLength: 0, prototype: "FnuDII" },
  "Bsh1285I": { name: "Bsh1285I", pattern: "CGRYCG", cutBefore: 4, cutBottom: 2, overhang: "", overhangType: '3prime', overhangLength: 2, prototype: "McrI" },
  "BshNI": { name: "BshNI", pattern: "GGYRCC", cutBefore: 1, cutBottom: 5, overhang: "", overhangType: '5prime', overhangLength: 4, prototype: "HgiCI" },
  "BshTI": { name: "BshTI", pattern: "ACCGGT", cutBefore: 1, cutBottom: 5, overhang: "CCGG", overhangType: '5prime', overhangLength: 4, prototype: "AgeI" },
  "BshVI": { name: "BshVI", pattern: "ATCGAT", cutBefore: 2, cutBottom: 4, overhang: "CG", overhangType: '5prime', overhangLength: 2, prototype: "ClaI" },
  "BsiEI": { name: "BsiEI", pattern: "CGRYCG", cutBefore: 4, cutBottom: 2, overhang: "", overhangType: '3prime', overhangLength: 2, prototype: "McrI" },
  "BsiHKAI": { name: "BsiHKAI", pattern: "GWGCWC", cutBefore: 5, cutBottom: 1, overhang: "", overhangType: '3prime', overhangLength: 4, prototype: "HgiAI" },
  "BsiHKCI": { name: "BsiHKCI", pattern: "CYCGRG", cutBefore: 1, cutBottom: 5, overhang: "", overhangType: '5prime', overhangLength: 4, prototype: "AvaI" },
  "BsiWI": { name: "BsiWI", pattern: "CGTACG", cutBefore: 1, cutBottom: 5, overhang: "GTAC", overhangType: '5prime', overhangLength: 4, prototype: "SplI", methylation: "5(4)" },
  "BslFI": { name: "BslFI", pattern: "GGGAC", cutBefore: 15, cutBottom: 19, overhang: "", overhangType: '5prime', overhangLength: 4, typeIIS: true, prototype: "FinI" },
  "BslI": { name: "BslI", pattern: "CCNNNNNNNGG", cutBefore: 7, cutBottom: 4, overhang: "", overhangType: '3prime', overhangLength: 3, prototype: "BsiYI", methylation: "2(4)" },
  "BsmAI": { name: "BsmAI", pattern: "GTCTC", cutBefore: 6, cutBottom: 10, overhang: "", overhangType: '5prime', overhangLength: 4, typeIIS: true, methylation: "?(5)" },
  "BsmBI": { name: "BsmBI", pattern: "CGTCTC", cutBefore: 7, cutBottom: 11, overhang: "", overhangType: '5prime', overhangLength: 4, typeIIS: true, prototype: "Esp3I", methylation: "4(5),-4(6)" },
  "BsmFI": { name: "BsmFI", pattern: "GGGAC", cutBefore: 15, cutBottom: 19, overhang: "", overhangType: '5prime', overhangLength: 4, typeIIS: true, prototype: "FinI", methylation: "?(6)" },
  "BsmI": { name: "BsmI", pattern: "GAATGC", cutBefore: 7, cutBottom: 5, overhang: "", overhangType: '3prime', overhangLength: 2, typeIIS: true },
  "BsnI": { name: "BsnI", pattern: "GGCC", cutBefore: 2, cutBottom: 2, overhang: "", overhangType: 'blunt', overhangLength: 0, prototype: "HaeIII" },
  "Bso31I": { name: "Bso31I", pattern: "GGTCTC", cutBefore: 7, cutBottom: 11, overhang: "", overhangType: '5prime', overhangLength: 4, typeIIS: true, prototype: "Eco31I" },
  "BsoBI": { name: "BsoBI", pattern: "CYCGRG", cutBefore: 1, cutBottom: 5, overhang: "", overhangType: '5prime', overhangLength: 4, prototype: "AvaI", methylation: "1(4)" },
  "Bsp119I": { name: "Bsp119I", pattern: "TTCGAA", cutBefore: 2, cutBottom: 4, overhang: "CG", overhangType: '5prime', overhangLength: 2, prototype: "AsuII" },
  "Bsp120I": { name: "Bsp120I", pattern: "GGGCCC", cutBefore: 1, cutBottom: 5, overhang: "GGCC", overhangType: '5prime', overhangLength: 4, prototype: "ApaI" },
  "Bsp1286I": { name: "Bsp1286I", pattern: "GDGCHC", cutBefore: 5, cutBottom: 1, overhang: "", overhangType: '3prime', overhangLength: 4, prototype: "SduI", methylation: "4(5)" },
  "Bsp13I": { name: "Bsp13I", pattern: "TCCGGA", cutBefore: 1, cutBottom: 5, overhang: "CCGG", overhangType: '5prime', overhangLength: 4, prototype: "BspMII" },
  "Bsp1407I": { name: "Bsp1407I", pattern: "TGTACA", cutBefore: 1, cutBottom: 5, overhang: "GTAC", overhangType: '5prime', overhangLength: 4 },
  "Bsp143I": { name: "Bsp143I", pattern: "GATC", cutBefore: 0, cutBottom: 4, overhang: "GATC", overhangType: '5prime', overhangLength: 4, prototype: "MboI" },
  "Bsp1720I": { name: "Bsp1720I", pattern: "GCTNAGC", cutBefore: 2, cutBottom: 5, overhang: "", overhangType: '5prime', overhangLength: 3, prototype: "EspI" },
  "Bsp19I": { name: "Bsp19I", pattern: "CCATGG", cutBefore: 1, cutBottom: 5, overhang: "CATG", overhangType: '5prime', overhangLength: 4, prototype: "NcoI" },
  "Bsp68I": { name: "Bsp68I", pattern: "TCGCGA", cutBefore: 3, cutBottom: 3, overhang: "", overhangType: 'blunt', overhangLength: 0, prototype: "NruI" },
  "BspACI": { name: "BspACI", pattern: "CCGC", cutBefore: 1, cutBottom: 3, overhang: "", overhangType: '5prime', overhangLength: 2, typeIIS: true, prototype: "AciI", methylation: "1(5)" },
  "BspCNI": { name: "BspCNI", pattern: "CTCAG", cutBefore: 14, cutBottom: 12, overhang: "", overhangType: '3prime', overhangLength: 2, typeIIS: true, prototype: "BseMII", methylation: "4(6),-4(6)" },
  "BspDI": { name: "BspDI", pattern: "ATCGAT", cutBefore: 2, cutBottom: 4, overhang: "CG", overhangType: '5prime', overhangLength: 2, prototype: "ClaI" },
  "BspEI": { name: "BspEI", pattern: "TCCGGA", cutBefore: 1, cutBottom: 5, overhang: "CCGG", overhangType: '5prime', overhangLength: 4, prototype: "BspMII" },
  "BspFNI": { name: "BspFNI", pattern: "CGCG", cutBefore: 2, cutBottom: 2, overhang: "", overhangType: 'blunt', overhangLength: 0, prototype: "FnuDII" },
  "BspHI": { name: "BspHI", pattern: "TCATGA", cutBefore: 1, cutBottom: 5, overhang: "CATG", overhangType: '5prime', overhangLength: 4, methylation: "3(6)" },
  "BspLI": { name: "BspLI", pattern: "GGNNCC", cutBefore: 3, cutBottom: 3, overhang: "", overhangType: 'blunt', overhangLength: 0, prototype: "NlaIV" },
  "BspMI": { name: "BspMI", pattern: "ACCTGC", cutBefore: 10, cutBottom: 14, overhang: "", overhangType: '5prime', overhangLength: 4, typeIIS: true, methylation: "?(5)" },
  "BspOI": { name: "BspOI", pattern: "GCTAGC", cutBefore: 5, cutBottom: 1, overhang: "CTAG", overhangType: '3prime', overhangLength: 4, prototype: "NheI" },
  "BspPI": { name: "BspPI", pattern: "GGATC", cutBefore: 9, cutBottom: 10, overhang: "", overhangType: '5prime', overhangLength: 1, typeIIS: true, prototype: "BinI" },
  "BspQI": { name: "BspQI", pattern: "GCTCTTC", cutBefore: 8, cutBottom: 11, overhang: "", overhangType: '5prime', overhangLength: 3, typeIIS: true, prototype: "SapI" },
  "BspTI": { name: "BspTI", pattern: "CTTAAG", cutBefore: 1, cutBottom: 5, overhang: "TTAA", overhangType: '5prime', overhangLength: 4, prototype: "AflII" },
  "BsrBI": { name: "BsrBI", pattern: "CCGCTC", cutBefore: 3, cutBottom: 3, overhang: "", overhangType: 'blunt', overhangLength: 0, typeIIS: true, methylation: "4(4),-4(4)" },
  "BsrDI": { name: "BsrDI", pattern: "GCAATG", cutBefore: 8, cutBottom: 6, overhang: "", overhangType: '3prime', overhangLength: 2, typeIIS: true },
  "BsrFI": { name: "BsrFI", pattern: "RCCGGY", cutBefore: 1, cutBottom: 5, overhang: "CCGG", overhangType: '5prime', overhangLength: 4, prototype: "Cfr10I", methylation: "2(5)" },
  "BsrGI": { name: "BsrGI", pattern: "TGTACA", cutBefore: 1, cutBottom: 5, overhang: "GTAC", overhangType: '5prime', overhangLength: 4, prototype: "Bsp1407I" },
  "BsrI": { name: "BsrI", pattern: "ACTGG", cutBefore: 6, cutBottom: 4, overhang: "", overhangType: '3prime', overhangLength: 2, typeIIS: true, methylation: "2(4),-1(4)" },
  "BsrSI": { name: "BsrSI", pattern: "ACTGG", cutBefore: 6, cutBottom: 4, overhang: "", overhangType: '3prime', overhangLength: 2, typeIIS: true, prototype: "BsrI" },
  "BssECI": { name: "BssECI", pattern: "CCNNGG", cutBefore: 1, cutBottom: 5, overhang: "", overhangType: '5prime', overhangLength: 4, prototype: "SecI", methylation: "1(4)" },
  "BssHII": { name: "BssHII", pattern: "GCGCGC", cutBefore: 1, cutBottom: 5, overhang: "CGCG", overhangType: '5prime', overhangLength: 4, prototype: "BsePI" },
  "BssMI": { name: "BssMI", pattern: "GATC", cutBefore: 0, cutBottom: 4, overhang: "GATC", overhangType: '5prime', overhangLength: 4, prototype: "MboI" },
  "BssNAI": { name: "BssNAI", pattern: "GTATAC", cutBefore: 3, cutBottom: 3, overhang: "", overhangType: 'blunt', overhangLength: 0, prototype: "SnaI" },
  "BssNI": { name: "BssNI", pattern: "GRCGYC", cutBefore: 2, cutBottom: 4, overhang: "CG", overhangType: '5prime', overhangLength: 2, prototype: "AcyI" },
  "BssSI": { name: "BssSI", pattern: "CACGAG", cutBefore: 1, cutBottom: 5, overhang: "", overhangType: '5prime', overhangLength: 4, typeIIS: true, prototype: "BsiI", methylation: "5(6),-1(4)" },
  "BssT1I": { name: "BssT1I", pattern: "CCWWGG", cutBefore: 1, cutBottom: 5, overhang: "", overhangType: '5prime', overhangLength: 4, prototype: "StyI" },
  "Bst1107I": { name: "Bst1107I", pattern: "GTATAC", cutBefore: 3, cutBottom: 3, overhang: "", overhangType: 'blunt', overhangLength: 0, prototype: "SnaI" },
  "Bst2BI": { name: "Bst2BI", pattern: "CACGAG", cutBefore: 1, cutBottom: 5, overhang: "", overhangType: '5prime', overhangLength: 4, typeIIS: true, prototype: "BsiI" },
  "Bst2UI": { name: "Bst2UI", pattern: "CCWGG", cutBefore: 2, cutBottom: 3, overhang: "", overhangType: '5prime', overhangLength: 1, prototype: "EcoRII" },
  "Bst4CI": { name: "Bst4CI", pattern: "ACNGT", cutBefore: 3, cutBottom: 2, overhang: "", overhangType: '3prime', overhangLength: 1, prototype: "Tsp4CI" },
  "Bst6I": { name: "Bst6I", pattern: "CTCTTC", cutBefore: 7, cutBottom: 10, overhang: "", overhangType: '5prime', overhangLength: 3, typeIIS: true, prototype: "Ksp632I" },
  "Bst98I": { name: "Bst98I", pattern: "CTTAAG", cutBefore: 1, cutBottom: 5, overhang: "TTAA", overhangType: '5prime', overhangLength: 4, prototype: "AflII" },
  "BstACI": { name: "BstACI", pattern: "GRCGYC", cutBefore: 2, cutBottom: 4, overhang: "CG", overhangType: '5prime', overhangLength: 2, prototype: "AcyI" },
  "BstAFI": { name: "BstAFI", pattern: "CTTAAG", cutBefore: 1, cutBottom: 5, overhang: "TTAA", overhangType: '5prime', overhangLength: 4, prototype: "AflII" },
  "BstAPI": { name: "BstAPI", pattern: "GCANNNNNTGC", cutBefore: 7, cutBottom: 4, overhang: "", overhangType: '3prime', overhangLength: 3, prototype: "ApaBI", methylation: "3(6)" },
  "BstAUI": { name: "BstAUI", pattern: "TGTACA", cutBefore: 1, cutBottom: 5, overhang: "GTAC", overhangType: '5prime', overhangLength: 4, prototype: "Bsp1407I" },
  "BstBAI": { name: "BstBAI", pattern: "YACGTR", cutBefore: 3, cutBottom: 3, overhang: "", overhangType: 'blunt', overhangLength: 0, prototype: "BsaAI" },
  "BstBI": { name: "BstBI", pattern: "TTCGAA", cutBefore: 2, cutBottom: 4, overhang: "CG", overhangType: '5prime', overhangLength: 2, prototype: "AsuII" },
  "BstC8I": { name: "BstC8I", pattern: "GCNNGC", cutBefore: 3, cutBottom: 3, overhang: "", overhangType: 'blunt', overhangLength: 0, prototype: "Cac8I", methylation: "2(5)" },
  "BstDEI": { name: "BstDEI", pattern: "CTNAG", cutBefore: 1, cutBottom: 4, overhang: "", overhangType: '5prime', overhangLength: 3, prototype: "DdeI" },
  "BstDSI": { name: "BstDSI", pattern: "CCRYGG", cutBefore: 1, cutBottom: 5, overhang: "", overhangType: '5prime', overhangLength: 4, prototype: "DsaI" },
  "BstEII": { name: "BstEII", pattern: "GGTNACC", cutBefore: 1, cutBottom: 6, overhang: "", overhangType: '5prime', overhangLength: 5, methylation: "5(6)" },
  "BstENI": { name: "BstENI", pattern: "CCTNNNNNAGG", cutBefore: 5, cutBottom: 6, overhang: "", overhangType: '5prime', overhangLength: 1, prototype: "EcoNI" },
  "BstF5I": { name: "BstF5I", pattern: "GGATG", cutBefore: 7, cutBottom: 5, overhang: "", overhangType: '3prime', overhangLength: 2, typeIIS: true, prototype: "FokI", methylation: "-2(6)" },
  "BstFI": { name: "BstFI", pattern: "AAGCTT", cutBefore: 1, cutBottom: 5, overhang: "AGCT", overhangType: '5prime', overhangLength: 4, prototype: "HindIII" },
  "BstFNI": { name: "BstFNI", pattern: "CGCG", cutBefore: 2, cutBottom: 2, overhang: "", overhangType: 'blunt', overhangLength: 0, prototype: "FnuDII" },
  "BstH2I": { name: "BstH2I", pattern: "RGCGCY", cutBefore: 5, cutBottom: 1, overhang: "GCGC", overhangType: '3prime', overhangLength: 4, prototype: "HaeII" },
  "BstHHI": { name: "BstHHI", pattern: "GCGC", cutBefore: 3, cutBottom: 1, overhang: "CG", overhangType: '3prime', overhangLength: 2, prototype: "HhaI" },
  "BstKTI": { name: "BstKTI", pattern: "GATC", cutBefore: 3, cutBottom: 1, overhang: "AT", overhangType: '3prime', overhangLength: 2, prototype: "MboI" },
  "BstMAI": { name: "BstMAI", pattern: "GTCTC", cutBefore: 6, cutBottom: 10, overhang: "", overhangType: '5prime', overhangLength: 4, typeIIS: true, prototype: "BsmAI" },
  "BstMBI": { name: "BstMBI", pattern: "GATC", cutBefore: 0, cutBottom: 4, overhang: "GATC", overhangType: '5prime', overhangLength: 4, prototype: "MboI" },
  "BstMCI": { name: "BstMCI", pattern: "CGRYCG", cutBefore: 4, cutBottom: 2, overhang: "", overhangType: '3prime', overhangLength: 2, prototype: "McrI" },
  "BstMWI": { name: "BstMWI", pattern: "GCNNNNNNNGC", cutBefore: 7, cutBottom: 4, overhang: "", overhangType: '3prime', overhangLength: 3, prototype: "MwoI" },
  "BstNI": { name: "BstNI", pattern: "CCWGG", cutBefore: 2, cutBottom: 3, overhang: "", overhangType: '5prime', overhangLength: 1, prototype: "EcoRII", methylation: "2(4)" },
  "BstNSI": { name: "BstNSI", pattern: "RCATGY", cutBefore: 5, cutBottom: 1, overhang: "CATG", overhangType: '3prime', overhangLength: 4, prototype: "NspI" },
  "BstOI": { name: "BstOI", pattern: "CCWGG", cutBefore: 2, cutBottom: 3, overhang: "", overhangType: '5prime', overhangLength: 1, prototype: "EcoRII" },
  "BstPAI": { name: "BstPAI", pattern: "GACNNNNGTC", cutBefore: 5, cutBottom: 5, overhang: "", overhangType: 'blunt', overhangLength: 0, prototype: "PshAI" },
  "BstSCI": { name: "BstSCI", pattern: "CCNGG", cutBefore: 0, cutBottom: 5, overhang: "", overhangType: '5prime', overhangLength: 5, prototype: "ScrFI" },
  "BstSFI": { name: "BstSFI", pattern: "CTRYAG", cutBefore: 1, cutBottom: 5, overhang: "", overhangType: '5prime', overhangLength: 4, prototype: "SfeI" },
  "BstSLI": { name: "BstSLI", pattern: "GKGCMC", cutBefore: 5, cutBottom: 1, overhang: "", overhangType: '3prime', overhangLength: 4, prototype: "BseSI" },
  "BstSNI": { name: "BstSNI", pattern: "TACGTA", cutBefore: 3, cutBottom: 3, overhang: "", overhangType: 'blunt', overhangLength: 0, prototype: "SnaBI" },
  "BstUI": { name: "BstUI", pattern: "CGCG", cutBefore: 2, cutBottom: 2, overhang: "", overhangType: 'blunt', overhangLength: 0, prototype: "FnuDII", methylation: "1(5)" },
  "BstV1I": { name: "BstV1I", pattern: "GCAGC", cutBefore: 13, cutBottom: 17, overhang: "", overhangType: '5prime', overhangLength: 4, typeIIS: true, prototype: "BbvI" },
  "BstV2I": { name: "BstV2I", pattern: "GAAGAC", cutBefore: 8, cutBottom: 12, overhang: "", overhangType: '5prime', overhangLength: 4, typeIIS: true, prototype: "BbvII" },
  "BstX2I": { name: "BstX2I", pattern: "RGATCY", cutBefore: 1, cutBottom: 5, overhang: "GATC", overhangType: '5prime', overhangLength: 4, prototype: "XhoII" },
  "BstXI": { name: "BstXI", pattern: "CCANNNNNNTGG", cutBefore: 8, cutBottom: 4, overhang: "", overhangType: '3prime', overhangLength: 4, methylation: "3(6)" },
  "BstYI": { name: "BstYI", pattern: "RGATCY", cutBefore: 1, cutBottom: 5, overhang: "GATC", overhangType: '5prime', overhangLength: 4, prototype: "XhoII", methylation: "5(4)" },
  "BstZ17I": { name: "BstZ17I", pattern: "GTATAC", cutBefore: 3, cutBottom: 3, overhang: "", overhangType: 'blunt', overhangLength: 0, prototype: "SnaI" },
  "BstZI": { name: "BstZI", pattern: "CGGCCG", cutBefore: 1, cutBottom: 5, overhang: "GGCC", overhangType: '5prime', overhangLength: 4, prototype: "XmaIII" },
  "Bsu15I": { name: "Bsu15I", pattern: "ATCGAT", cutBefore: 2, cutBottom: 4, overhang: "CG", overhangType: '5prime', overhangLength: 2, prototype: "ClaI", methylation: "5(6)" },
  "Bsu36I": { name: "Bsu36I", pattern: "CCTNAGG", cutBefore: 2, cutBottom: 5, overhang: "", overhangType: '5prime', overhangLength: 3, prototype: "SauI", methylation: "2(4)" },
  "BsuI": { name: "BsuI", pattern: "GTATCC", cutBefore: 12, cutBottom: 11, overhang: "", overhangType: '3prime', overhangLength: 1, typeIIS: true, prototype: "BciVI" },
  "BsuRI": { name: "BsuRI", pattern: "GGCC", cutBefore: 2, cutBottom: 2, overhang: "", overhangType: 'blunt', overhangLength: 0, prototype: "HaeIII", methylation: "3(5)" },
  "BtgI": { name: "BtgI", pattern: "CCRYGG", cutBefore: 1, cutBottom: 5, overhang: "", overhangType: '5prime', overhangLength: 4, prototype: "DsaI" },
  "BtgZI": { name: "BtgZI", pattern: "GCGATG", cutBefore: 16, cutBottom: 20, overhang: "", overhangType: '5prime', overhangLength: 4, typeIIS: true, methylation: "?(6)" },
  "BtrI": { name: "BtrI", pattern: "CACGTC", cutBefore: 3, cutBottom: 3, overhang: "", overhangType: 'blunt', overhangLength: 0, typeIIS: true },
  "BtsCI": { name: "BtsCI", pattern: "GGATG", cutBefore: 7, cutBottom: 5, overhang: "", overhangType: '3prime', overhangLength: 2, typeIIS: true, prototype: "FokI" },
  "BtsI": { name: "BtsI", pattern: "GCAGTG", cutBefore: 8, cutBottom: 6, overhang: "", overhangType: '3prime', overhangLength: 2, typeIIS: true },
  "BtsIMutI": { name: "BtsIMutI", pattern: "CAGTG", cutBefore: 7, cutBottom: 5, overhang: "", overhangType: '3prime', overhangLength: 2, typeIIS: true },
  "BtuMI": { name: "BtuMI", pattern: "TCGCGA", cutBefore: 3, cutBottom: 3, overhang: "", overhangType: 'blunt', overhangLength: 0, prototype: "NruI" },
  "BveI": { name: "BveI", pattern: "ACCTGC", cutBefore: 10, cutBottom: 14, overhang: "", overhangType: '5prime', overhangLength: 4, typeIIS: true, prototype: "BspMI" },
  "Cac8I": { name: "Cac8I", pattern: "GCNNGC", cutBefore: 3, cutBottom: 3, overhang: "", overhangType: 'blunt', overhangLength: 0, methylation: "2(5)" },
  "CaiI": { name: "CaiI", pattern: "CAGNNNCTG", cutBefore: 6, cutBottom: 3, overhang: "", overhangType: '3prime', overhangLength: 3, prototype: "AlwNI" },
  "CciI": { name: "CciI", pattern: "TCATGA", cutBefore: 1, cutBottom: 5, overhang: "CATG", overhangType: '5prime', overhangLength: 4, prototype: "BspHI" },
  "CciNI": { name: "CciNI", pattern: "GCGGCCGC", cutBefore: 2, cutBottom: 6, overhang: "GGCC", overhangType: '5prime', overhangLength: 4, prototype: "NotI" },
  "CelII": { name: "CelII", pattern: "GCTNAGC", cutBefore: 2, cutBottom: 5, overhang: "", overhangType: '5prime', overhangLength: 3, prototype: "EspI" },
  "CfoI": { name: "CfoI", pattern: "GCGC", cutBefore: 3, cutBottom: 1, overhang: "CG", overhangType: '3prime', overhangLength: 2, prototype: "HhaI" },
  "Cfr10I": { name: "Cfr10I", pattern: "RCCGGY", cutBefore: 1, cutBottom: 5, overhang: "CCGG", overhangType: '5prime', overhangLength: 4, methylation: "2(5)" },
  "Cfr13I": { name: "Cfr13I", pattern: "GGNCC", cutBefore: 1, cutBottom: 4, overhang: "", overhangType: '5prime', overhangLength: 3, prototype: "AsuI", methylation: "4(5)" },
  "Cfr42I": { name: "Cfr42I", pattern: "CCGCGG", cutBefore: 4, cutBottom: 2, overhang: "GC", overhangType: '3prime', overhangLength: 2, prototype: "SacII", methylation: "?(5)" },
  "Cfr9I": { name: "Cfr9I", pattern: "CCCGGG", cutBefore: 1, cutBottom: 5, overhang: "CCGG", overhangType: '5prime', overhangLength: 4, prototype: "SmaI", methylation: "2(4)" },
  "ClaI": { name: "ClaI", pattern: "ATCGAT", cutBefore: 2, cutBottom: 4, overhang: "CG", overhangType: '5prime', overhangLength: 2, methylation: "5(6)" },
  "CpoI": { name: "CpoI", pattern: "CGGWCCG", cutBefore: 2, cutBottom: 5, overhang: "", overhangType: '5prime', overhangLength: 3, prototype: "RsrII" },
  "CseI": { name: "CseI", pattern: "GACGC", cutBefore: 10, cutBottom: 15, overhang: "", overhangType: '5prime', overhangLength: 5, typeIIS: true, prototype: "HgaI" },
  "Csp45I": { name: "Csp45I", pattern: "TTCGAA", cutBefore: 2, cutBottom: 4, overhang: "CG", overhangType: '5prime', overhangLength: 2, prototype: "AsuII" },
  "Csp6I": { name: "Csp6I", pattern: "GTAC", cutBefore: 1, cutBottom: 3, overhang: "TA", overhangType: '5prime', overhangLength: 2, prototype: "RsaI" },
  "CspI": { name: "CspI", pattern: "CGGWCCG", cutBefore: 2, cutBottom: 5, overhang: "", overhangType: '5prime', overhangLength: 3, prototype: "RsrII" },
  "CviJI": { name: "CviJI", pattern: "RGCY", cutBefore: 2, cutBottom: 2, overhang: "", overhangType: 'blunt', overhangLength: 0, methylation: "3(5),-3(5)" },
  "CviQI": { name: "CviQI", pattern: "GTAC", cutBefore: 1, cutBottom: 3, overhang: "TA", overhangType: '5prime', overhangLength: 2, prototype: "RsaI", methylation: "3(6)" },
  "DdeI": { name: "DdeI", pattern: "CTNAG", cutBefore: 1, cutBottom: 4, overhang: "", overhangType: '5prime', overhangLength: 3, methylation: "1(5)" },
  "DinI": { name: "DinI", pattern: "GGCGCC", cutBefore: 3, cutBottom: 3, overhang: "", overhangType: 'blunt', overhangLength: 0, prototype: "NarI" },
  "DpnI": { name: "DpnI", pattern: "GATC", cutBefore: 2, cutBottom: 2, overhang: "", overhangType: 'blunt', overhangLength: 0 },
  "DpnII": { name: "DpnII", pattern: "GATC", cutBefore: 0, cutBottom: 4, overhang: "GATC", overhangType: '5prime', overhangLength: 4, prototype: "MboI", methylation: "2(6)" },
  "DraI": { name: "DraI", pattern: "TTTAAA", cutBefore: 3, cutBottom: 3, overhang: "", overhangType: 'blunt', overhangLength: 0, prototype: "AhaIII", methylation: "6(6)" },
  "DraIII": { name: "DraIII", pattern: "CACNNNGTG", cutBefore: 6, cutBottom: 3, overhang: "", overhangType: '3prime', overhangLength: 3, methylation: "2(6)" },
  "DrdI": { name: "DrdI", pattern: "GACNNNNNNGTC", cutBefore: 7, cutBottom: 5, overhang: "", overhangType: '3prime', overhangLength: 2, methylation: "2(6)" },
  "DriI": { name: "DriI", pattern: "GACNNNNNGTC", cutBefore: 6, cutBottom: 5, overhang: "", overhangType: '3prime', overhangLength: 1, prototype: "Eam1105I" },
  "DsaI": { name: "DsaI", pattern: "CCRYGG", cutBefore: 1, cutBottom: 5, overhang: "", overhangType: '5prime', overhangLength: 4 },
  "DseDI": { name: "DseDI", pattern: "GACNNNNNNGTC", cutBefore: 7, cutBottom: 5, overhang: "", overhangType: '3prime', overhangLength: 2, prototype: "DrdI" },
  "EaeI": { name: "EaeI", pattern: "YGGCCR", cutBefore: 1, cutBottom: 5, overhang: "GGCC", overhangType: '5prime', overhangLength: 4, prototype: "CfrI", methylation: "4(5)" },
  "EagI": { name: "EagI", pattern: "CGGCCG", cutBefore: 1, cutBottom: 5, overhang: "GGCC", overhangType: '5prime', overhangLength: 4, prototype: "XmaIII", methylation: "4(5)" },
  "Eam1104I": { name: "Eam1104I", pattern: "CTCTTC", cutBefore: 7, cutBottom: 10, overhang: "", overhangType: '5prime', overhangLength: 3, typeIIS: true, prototype: "Ksp632I" },
  "Eam1105I": { name: "Eam1105I", pattern: "GACNNNNNGTC", cutBefore: 6, cutBottom: 5, overhang: "", overhangType: '3prime', overhangLength: 1 },
  "EarI": { name: "EarI", pattern: "CTCTTC", cutBefore: 7, cutBottom: 10, overhang: "", overhangType: '5prime', overhangLength: 3, typeIIS: true, prototype: "Ksp632I", methylation: "-5(6)" },
  "EciI": { name: "EciI", pattern: "GGCGGA", cutBefore: 17, cutBottom: 15, overhang: "", overhangType: '3prime', overhangLength: 2, typeIIS: true },
  "Ecl136II": { name: "Ecl136II", pattern: "GAGCTC", cutBefore: 3, cutBottom: 3, overhang: "", overhangType: 'blunt', overhangLength: 0, prototype: "SacI" },
  "EclHKI": { name: "EclHKI", pattern: "GACNNNNNGTC", cutBefore: 6, cutBottom: 5, overhang: "", overhangType: '3prime', overhangLength: 1, prototype: "Eam1105I" },
  "Eco105I": { name: "Eco105I", pattern: "TACGTA", cutBefore: 3, cutBottom: 3, overhang: "", overhangType: 'blunt', overhangLength: 0, prototype: "SnaBI" },
  "Eco130I": { name: "Eco130I", pattern: "CCWWGG", cutBefore: 1, cutBottom: 5, overhang: "", overhangType: '5prime', overhangLength: 4, prototype: "StyI" },
  "Eco147I": { name: "Eco147I", pattern: "AGGCCT", cutBefore: 3, cutBottom: 3, overhang: "", overhangType: 'blunt', overhangLength: 0, prototype: "StuI" },
  "Eco24I": { name: "Eco24I", pattern: "GRGCYC", cutBefore: 5, cutBottom: 1, overhang: "", overhangType: '3prime', overhangLength: 4, prototype: "HgiJII" },
  "Eco31I": { name: "Eco31I", pattern: "GGTCTC", cutBefore: 7, cutBottom: 11, overhang: "", overhangType: '5prime', overhangLength: 4, typeIIS: true, methylation: "-4(6)" },
  "Eco32I": { name: "Eco32I", pattern: "GATATC", cutBefore: 3, cutBottom: 3, overhang: "", overhangType: 'blunt', overhangLength: 0, prototype: "EcoRV" },
  "Eco47I": { name: "Eco47I", pattern: "GGWCC", cutBefore: 1, cutBottom: 4, overhang: "", overhangType: '5prime', overhangLength: 3, prototype: "AvaII" },
  "Eco47III": { name: "Eco47III", pattern: "AGCGCT", cutBefore: 3, cutBottom: 3, overhang: "", overhangType: 'blunt', overhangLength: 0 },
  "Eco52I": { name: "Eco52I", pattern: "CGGCCG", cutBefore: 1, cutBottom: 5, overhang: "GGCC", overhangType: '5prime', overhangLength: 4, prototype: "XmaIII" },
  "Eco53kI": { name: "Eco53kI", pattern: "GAGCTC", cutBefore: 3, cutBottom: 3, overhang: "", overhangType: 'blunt', overhangLength: 0, prototype: "SacI" },
  "Eco57I": { name: "Eco57I", pattern: "CTGAAG", cutBefore: 22, cutBottom: 20, overhang: "", overhangType: '3prime', overhangLength: 2, typeIIS: true, methylation: "5(6)" },
  "Eco72I": { name: "Eco72I", pattern: "CACGTG", cutBefore: 3, cutBottom: 3, overhang: "", overhangType: 'blunt', overhangLength: 0, prototype: "PmaCI" },
  "Eco81I": { name: "Eco81I", pattern: "CCTNAGG", cutBefore: 2, cutBottom: 5, overhang: "", overhangType: '5prime', overhangLength: 3, prototype: "SauI" },
  "Eco88I": { name: "Eco88I", pattern: "CYCGRG", cutBefore: 1, cutBottom: 5, overhang: "", overhangType: '5prime', overhangLength: 4, prototype: "AvaI" },
  "Eco91I": { name: "Eco91I", pattern: "GGTNACC", cutBefore: 1, cutBottom: 6, overhang: "", overhangType: '5prime', overhangLength: 5, prototype: "BstEII" },
  "EcoICRI": { name: "EcoICRI", pattern: "GAGCTC", cutBefore: 3, cutBottom: 3, overhang: "", overhangType: 'blunt', overhangLength: 0, prototype: "SacI" },
  "EcoNI": { name: "EcoNI", pattern: "CCTNNNNNAGG", cutBefore: 5, cutBottom: 6, overhang: "", overhangType: '5prime', overhangLength: 1, methylation: "2(4)" },
  "EcoO109I": { name: "EcoO109I", pattern: "RGGNCCY", cutBefore: 2, cutBottom: 5, overhang: "", overhangType: '5prime', overhangLength: 3, prototype: "DraII", methylation: "5(5)" },
  "EcoRI": { name: "EcoRI", pattern: "GAATTC", cutBefore: 1, cutBottom: 5, overhang: "AATT", overhangType: '5prime', overhangLength: 4, methylation: "3(6)" },
  "EcoRII": { name: "EcoRII", pattern: "CCWGG", cutBefore: 0, cutBottom: 5, overhang: "", overhangType: '5prime', overhangLength: 5, methylation: "2(5)" },
  "EcoRV": { name: "EcoRV", pattern: "GATATC", cutBefore: 3, cutBottom: 3, overhang: "", overhangType: 'blunt', overhangLength: 0, methylation: "2(6)" },
  "EcoT38I": { name: "EcoT38I", pattern: "GRGCYC", cutBefore: 5, cutBottom: 1, overhang: "", overhangType: '3prime', overhangLength: 4, prototype: "HgiJII", methylation: "4(5)" },
  "EgeI": { name: "EgeI", pattern: "GGCGCC", cutBefore: 3, cutBottom: 3, overhang: "", overhangType: 'blunt', overhangLength: 0, prototype: "NarI" },
  "EheI": { name: "EheI", pattern: "GGCGCC", cutBefore: 3, cutBottom: 3, overhang: "", overhangType: 'blunt', overhangLength: 0, prototype: "NarI" },
  "ErhI": { name: "ErhI", pattern: "CCWWGG", cutBefore: 1, cutBottom: 5, overhang: "", overhangType: '5prime', overhangLength: 4, prototype: "StyI" },
  "Esp3I": { name: "Esp3I", pattern: "CGTCTC", cutBefore: 7, cutBottom: 11, overhang: "", overhangType: '5prime', overhangLength: 4, typeIIS: true, methylation: "4(5),-4(6)" },
  "FaeI": { name: "FaeI", pattern: "CATG", cutBefore: 4, cutBottom: 0, overhang: "CATG", overhangType: '3prime', overhangLength: 4, prototype: "NlaIII" },
  "FaiI": { name: "FaiI", pattern: "YATR", cutBefore: 2, cutBottom: 2, overhang: "", overhangType: 'blunt', overhangLength: 0 },
  "FaqI": { name: "FaqI", pattern: "GGGAC", cutBefore: 15, cutBottom: 19, overhang: "", overhangType: '5prime', overhangLength: 4, typeIIS: true, prototype: "FinI" },
  "FatI": { name: "FatI", pattern: "CATG", cutBefore: 0, cutBottom: 4, overhang: "CATG", overhangType: '5prime', overhangLength: 4, prototype: "NlaIII", methylation: "1(5)" },
  "FauI": { name: "FauI", pattern: "CCCGC", cutBefore: 9, cutBottom: 11, overhang: "", overhangType: '5prime', overhangLength: 2, typeIIS: true },
  "FauNDI": { name: "FauNDI", pattern: "CATATG", cutBefore: 2, cutBottom: 4, overhang: "TA", overhangType: '5prime', overhangLength: 2, prototype: "NdeI" },
  "FblI": { name: "FblI", pattern: "GTMKAC", cutBefore: 2, cutBottom: 4, overhang: "", overhangType: '5prime', overhangLength: 2, prototype: "AccI" },
  "Fnu4HI": { name: "Fnu4HI", pattern: "GCNGC", cutBefore: 2, cutBottom: 3, overhang: "", overhangType: '5prime', overhangLength: 1, methylation: "2(5)" },
  "FokI": { name: "FokI", pattern: "GGATG", cutBefore: 14, cutBottom: 18, overhang: "", overhangType: '5prime', overhangLength: 4, typeIIS: true, methylation: "3(6),-2(6)" },
  "FriOI": { name: "FriOI", pattern: "GRGCYC", cutBefore: 5, cutBottom: 1, overhang: "", overhangType: '3prime', overhangLength: 4, prototype: "HgiJII" },
  "FseI": { name: "FseI", pattern: "GGCCGGCC", cutBefore: 6, cutBottom: 2, overhang: "CCGG", overhangType: '3prime', overhangLength: 4, methylation: "?(5)" },
  "Fsp4HI": { name: "Fsp4HI", pattern: "GCNGC", cutBefore: 2, cutBottom: 3, overhang: "", overhangType: '5prime', overhangLength: 1, prototype: "Fnu4HI", methylation: "2(5)" },
  "FspAI": { name: "FspAI", pattern: "RTGCGCAY", cutBefore: 4, cutBottom: 4, overhang: "", overhangType: 'blunt', overhangLength: 0 },
  "FspBI": { name: "FspBI", pattern: "CTAG", cutBefore: 1, cutBottom: 3, overhang: "TA", overhangType: '5prime', overhangLength: 2, prototype: "MaeI" },
  "FspI": { name: "FspI", pattern: "TGCGCA", cutBefore: 3, cutBottom: 3, overhang: "", overhangType: 'blunt', overhangLength: 0, prototype: "MstI", methylation: "?(5)" },
  "GlaI": { name: "GlaI", pattern: "GCGC", cutBefore: 2, cutBottom: 2, overhang: "", overhangType: 'blunt', overhangLength: 0 },
  "GluI": { name: "GluI", pattern: "GCNGC", cutBefore: 2, cutBottom: 3, overhang: "", overhangType: '5prime', overhangLength: 1, prototype: "BisI" },
  "GsaI": { name: "GsaI", pattern: "CCCAGC", cutBefore: 5, cutBottom: 1, overhang: "", overhangType: '3prime', overhangLength: 4, typeIIS: true, prototype: "BseYI" },
  "GsuI": { name: "GsuI", pattern: "CTGGAG", cutBefore: 22, cutBottom: 20, overhang: "", overhangType: '3prime', overhangLength: 2, typeIIS: true },
  "HaeII": { name: "HaeII", pattern: "RGCGCY", cutBefore: 5, cutBottom: 1, overhang: "GCGC", overhangType: '3prime', overhangLength: 4, methylation: "?(5)" },
  "HaeIII": { name: "HaeIII", pattern: "GGCC", cutBefore: 2, cutBottom: 2, overhang: "", overhangType: 'blunt', overhangLength: 0, methylation: "3(5)" },
  "HgaI": { name: "HgaI", pattern: "GACGC", cutBefore: 10, cutBottom: 15, overhang: "", overhangType: '5prime', overhangLength: 5, typeIIS: true, methylation: "3(5),-2(5)" },
  "HhaI": { name: "HhaI", pattern: "GCGC", cutBefore: 3, cutBottom: 1, overhang: "CG", overhangType: '3prime', overhangLength: 2, methylation: "2(5)" },
  "Hin1I": { name: "Hin1I", pattern: "GRCGYC", cutBefore: 2, cutBottom: 4, overhang: "CG", overhangType: '5prime', overhangLength: 2, prototype: "AcyI" },
  "Hin1II": { name: "Hin1II", pattern: "CATG", cutBefore: 4, cutBottom: 0, overhang: "CATG", overhangType: '3prime', overhangLength: 4, prototype: "NlaIII" },
  "Hin6I": { name: "Hin6I", pattern: "GCGC", cutBefore: 1, cutBottom: 3, overhang: "CG", overhangType: '5prime', overhangLength: 2, prototype: "HhaI" },
  "HincII": { name: "HincII", pattern: "GTYRAC", cutBefore: 3, cutBottom: 3, overhang: "", overhangType: 'blunt', overhangLength: 0, prototype: "HindII", methylation: "5(6)" },
  "HindII": { name: "HindII", pattern: "GTYRAC", cutBefore: 3, cutBottom: 3, overhang: "", overhangType: 'blunt', overhangLength: 0, methylation: "5(6)" },
  "HindIII": { name: "HindIII", pattern: "AAGCTT", cutBefore: 1, cutBottom: 5, overhang: "AGCT", overhangType: '5prime', overhangLength: 4, methylation: "1(6)" },
  "HinfI": { name: "HinfI", pattern: "GANTC", cutBefore: 1, cutBottom: 4, overhang: "", overhangType: '5prime', overhangLength: 3, methylation: "2(6)" },
  "HinP1I": { name: "HinP1I", pattern: "GCGC", cutBefore: 1, cutBottom: 3, overhang: "CG", overhangType: '5prime', overhangLength: 2, prototype: "HhaI", methylation: "2(5)" },
  "HpaI": { name: "HpaI", pattern: "GTTAAC", cutBefore: 3, cutBottom: 3, overhang: "", overhangType: 'blunt', overhangLength: 0, methylation: "5(6)" },
  "HpaII": { name: "HpaII", pattern: "CCGG", cutBefore: 1, cutBottom: 3, overhang: "CG", overhangType: '5prime', overhangLength: 2, methylation: "2(5)" },
  "HphI": { name: "HphI", pattern: "GGTGA", cutBefore: 13, cutBottom: 12, overhang: "", overhangType: '3prime', overhangLength: 1, typeIIS: true, methylation: "5(6)" },
  "Hpy166II": { name: "Hpy166II", pattern: "GTNNAC", cutBefore: 3, cutBottom: 3, overhang: "", overhangType: 'blunt', overhangLength: 0, prototype: "MjaIV" },
  "Hpy188I": { name: "Hpy188I", pattern: "TCNGA", cutBefore: 3, cutBottom: 2, overhang: "", overhangType: '3prime', overhangLength: 1, methylation: "5(6)" },
  "Hpy188III": { name: "Hpy188III", pattern: "TCNNGA", cutBefore: 2, cutBottom: 4, overhang: "", overhangType: '5prime', overhangLength: 2, prototype: "Hpy178III" },
  "Hpy8I": { name: "Hpy8I", pattern: "GTNNAC", cutBefore: 3, cutBottom: 3, overhang: "", overhangType: 'blunt', overhangLength: 0, prototype: "MjaIV", methylation: "5(6)" },
  "Hpy99I": { name: "Hpy99I", pattern: "CGWCG", cutBefore: 5, cutBottom: 0, overhang: "", overhangType: '3prime', overhangLength: 5, methylation: "4(4)" },
  "HpyAV": { name: "HpyAV", pattern: "CCTTC", cutBefore: 11, cutBottom: 10, overhang: "", overhangType: '3prime', overhangLength: 1, typeIIS: true, prototype: "Hin4II", methylation: "2(5),-3(6)" },
  "HpyCH4III": { name: "HpyCH4III", pattern: "ACNGT", cutBefore: 3, cutBottom: 2, overhang: "", overhangType: '3prime', overhangLength: 1, prototype: "Tsp4CI" },
  "HpyCH4IV": { name: "HpyCH4IV", pattern: "ACGT", cutBefore: 1, cutBottom: 3, overhang: "CG", overhangType: '5prime', overhangLength: 2, prototype: "MaeII", methylation: "2(5)" },
  "HpyCH4V": { name: "HpyCH4V", pattern: "TGCA", cutBefore: 2, cutBottom: 2, overhang: "", overhangType: 'blunt', overhangLength: 0, prototype: "CviRI" },
  "HpyF10VI": { name: "HpyF10VI", pattern: "GCNNNNNNNGC", cutBefore: 7, cutBottom: 4, overhang: "", overhangType: '3prime', overhangLength: 3, prototype: "MwoI" },
  "HpyF3I": { name: "HpyF3I", pattern: "CTNAG", cutBefore: 1, cutBottom: 4, overhang: "", overhangType: '5prime', overhangLength: 3, prototype: "DdeI" },
  "HpySE526I": { name: "HpySE526I", pattern: "ACGT", cutBefore: 1, cutBottom: 3, overhang: "CG", overhangType: '5prime', overhangLength: 2, prototype: "MaeII" },
  "Hsp92I": { name: "Hsp92I", pattern: "GRCGYC", cutBefore: 2, cutBottom: 4, overhang: "CG", overhangType: '5prime', overhangLength: 2, prototype: "AcyI" },
  "Hsp92II": { name: "Hsp92II", pattern: "CATG", cutBefore: 4, cutBottom: 0, overhang: "CATG", overhangType: '3prime', overhangLength: 4, prototype: "NlaIII" },
  "HspAI": { name: "HspAI", pattern: "GCGC", cutBefore: 1, cutBottom: 3, overhang: "CG", overhangType: '5prime', overhangLength: 2, prototype: "HhaI", methylation: "2(5)" },
  "KasI": { name: "KasI", pattern: "GGCGCC", cutBefore: 1, cutBottom: 5, overhang: "GCGC", overhangType: '5prime', overhangLength: 4, prototype: "NarI", methylation: "?(5)" },
  "Kpn2I": { name: "Kpn2I", pattern: "TCCGGA", cutBefore: 1, cutBottom: 5, overhang: "CCGG", overhangType: '5prime', overhangLength: 4, prototype: "BspMII", methylation: "?(5)" },
  "KpnI": { name: "KpnI", pattern: "GGTACC", cutBefore: 5, cutBottom: 1, overhang: "GTAC", overhangType: '3prime', overhangLength: 4, methylation: "4(6)" },
  "KroI": { name: "KroI", pattern: "GCCGGC", cutBefore: 1, cutBottom: 5, overhang: "CCGG", overhangType: '5prime', overhangLength: 4 },
  "KroNI": { name: "KroNI", pattern: "GCCGGC", cutBefore: 3, cutBottom: 3, overhang: "", overhangType: 'blunt', overhangLength: 0, prototype: "NaeI" },
  "Ksp22I": { name: "Ksp22I", pattern: "TGATCA", cutBefore: 1, cutBottom: 5, overhang: "GATC", overhangType: '5prime', overhangLength: 4, prototype: "BclI" },
  "KspAI": { name: "KspAI", pattern: "GTTAAC", cutBefore: 3, cutBottom: 3, overhang: "", overhangType: 'blunt', overhangLength: 0, prototype: "HpaI" },
  "KspI": { name: "KspI", pattern: "CCGCGG", cutBefore: 4, cutBottom: 2, overhang: "GC", overhangType: '3prime', overhangLength: 2, prototype: "SacII" },
  "Kzo9I": { name: "Kzo9I", pattern: "GATC", cutBefore: 0, cutBottom: 4, overhang: "GATC", overhangType: '5prime', overhangLength: 4, prototype: "MboI" },
  "LguI": { name: "LguI", pattern: "GCTCTTC", cutBefore: 8, cutBottom: 11, overhang: "", overhangType: '5prime', overhangLength: 3, typeIIS: true, prototype: "SapI" },
  "LmnI": { name: "LmnI", pattern: "GCTCC", cutBefore: 6, cutBottom: 4, overhang: "", overhangType: '3prime', overhangLength: 2, typeIIS: true },
  "Lsp1109I": { name: "Lsp1109I", pattern: "GCAGC", cutBefore: 13, cutBottom: 17, overhang: "", overhangType: '5prime', overhangLength: 4, typeIIS: true, prototype: "BbvI", methylation: "?(5)" },
  "LweI": { name: "LweI", pattern: "GCATC", cutBefore: 10, cutBottom: 14, overhang: "", overhangType: '5prime', overhangLength: 4, typeIIS: true, prototype: "SfaNI" },
  "MabI": { name: "MabI", pattern: "ACCWGGT", cutBefore: 1, cutBottom: 6, overhang: "", overhangType: '5prime', overhangLength: 5, prototype: "SexAI" },
  "MalI": { name: "MalI", pattern: "GATC", cutBefore: 2, cutBottom: 2, overhang: "", overhangType: 'blunt', overhangLength: 0, prototype: "DpnI" },
  "MamI": { name: "MamI", pattern: "GATNNNNATC", cutBefore: 5, cutBottom: 5, overhang: "", overhangType: 'blunt', overhangLength: 0, prototype: "BsaBI", methylation: "?(6)" },
  "MauBI": { name: "MauBI", pattern: "CGCGCGCG", cutBefore: 2, cutBottom: 6, overhang: "CGCG", overhangType: '5prime', overhangLength: 4 },
  "MbiI": { name: "MbiI", pattern: "CCGCTC", cutBefore: 3, cutBottom: 3, overhang: "", overhangType: 'blunt', overhangLength: 0, typeIIS: true, prototype: "BsrBI" },
  "MboI": { name: "MboI", pattern: "GATC", cutBefore: 0, cutBottom: 4, overhang: "GATC", overhangType: '5prime', overhangLength: 4, methylation: "2(6)" },
  "MboII": { name: "MboII", pattern: "GAAGA", cutBefore: 13, cutBottom: 12, overhang: "", overhangType: '3prime', overhangLength: 1, typeIIS: true, methylation: "?(4),-2(4)" },
  "MfeI": { name: "MfeI", pattern: "CAATTG", cutBefore: 1, cutBottom: 5, overhang: "AATT", overhangType: '5prime', overhangLength: 4, methylation: "3(6)" },
  "MhlI": { name: "MhlI", pattern: "GDGCHC", cutBefore: 5, cutBottom: 1, overhang: "", overhangType: '3prime', overhangLength: 4, prototype: "SduI" },
  "MlsI": { name: "MlsI", pattern: "TGGCCA", cutBefore: 3, cutBottom: 3, overhang: "", overhangType: 'blunt', overhangLength: 0, prototype: "BalI" },
  "MluCI": { name: "MluCI", pattern: "AATT", cutBefore: 0, cutBottom: 4, overhang: "AATT", overhangType: '5prime', overhangLength: 4, prototype: "TspEI", methylation: "2(6)" },
  "MluI": { name: "MluI", pattern: "ACGCGT", cutBefore: 1, cutBottom: 5, overhang: "CGCG", overhangType: '5prime', overhangLength: 4, methylation: "2(4)" },
  "Mly113I": { name: "Mly113I", pattern: "GGCGCC", cutBefore: 2, cutBottom: 4, overhang: "CG", overhangType: '5prime', overhangLength: 2, prototype: "NarI" },
  "MlyI": { name: "MlyI", pattern: "GAGTC", cutBefore: 10, cutBottom: 10, overhang: "", overhangType: 'blunt', overhangLength: 0, typeIIS: true, prototype: "PleI", methylation: "2(6)" },
  "MmeI": { name: "MmeI", pattern: "TCCRAC", cutBefore: 26, cutBottom: 24, overhang: "", overhangType: '3prime', overhangLength: 2, typeIIS: true, methylation: "5(6)" },
  "MnlI": { name: "MnlI", pattern: "CCTC", cutBefore: 11, cutBottom: 10, overhang: "", overhangType: '3prime', overhangLength: 1, typeIIS: true, methylation: "-2(6)" },
  "Mox20I": { name: "Mox20I", pattern: "TGGCCA", cutBefore: 3, cutBottom: 3, overhang: "", overhangType: 'blunt', overhangLength: 0, prototype: "BalI" },
  "Mph1103I": { name: "Mph1103I", pattern: "ATGCAT", cutBefore: 5, cutBottom: 1, overhang: "TGCA", overhangType: '3prime', overhangLength: 4, prototype: "AvaIII" },
  "MreI": { name: "MreI", pattern: "CGCCGGCG", cutBefore: 2, cutBottom: 6, overhang: "CCGG", overhangType: '5prime', overhangLength: 4, prototype: "Sse232I" },
  "MroI": { name: "MroI", pattern: "TCCGGA", cutBefore: 1, cutBottom: 5, overhang: "CCGG", overhangType: '5prime', overhangLength: 4, prototype: "BspMII" },
  "MroNI": { name: "MroNI", pattern: "GCCGGC", cutBefore: 1, cutBottom: 5, overhang: "CCGG", overhangType: '5prime', overhangLength: 4, prototype: "NaeI" },
  "MroXI": { name: "MroXI", pattern: "GAANNNNTTC", cutBefore: 5, cutBottom: 5, overhang: "", overhangType: 'blunt', overhangLength: 0, prototype: "XmnI" },
  "MscI": { name: "MscI", pattern: "TGGCCA", cutBefore: 3, cutBottom: 3, overhang: "", overhangType: 'blunt', overhangLength: 0, prototype: "BalI", methylation: "4(4)" },
  "MseI": { name: "MseI", pattern: "TTAA", cutBefore: 1, cutBottom: 3, overhang: "TA", overhangType: '5prime', overhangLength: 2, methylation: "4(6)" },
  "MslI": { name: "MslI", pattern: "CAYNNNNRTG", cutBefore: 5, cutBottom: 5, overhang: "", overhangType: 'blunt', overhangLength: 0 },
  "Msp20I": { name: "Msp20I", pattern: "TGGCCA", cutBefore: 3, cutBottom: 3, overhang: "", overhangType: 'blunt', overhangLength: 0, prototype: "BalI" },
  "MspA1I": { name: "MspA1I", pattern: "CMGCKG", cutBefore: 3, cutBottom: 3, overhang: "", overhangType: 'blunt', overhangLength: 0, prototype: "NspBII", methylation: "?(4)" },
  "MspI": { name: "MspI", pattern: "CCGG", cutBefore: 1, cutBottom: 3, overhang: "CG", overhangType: '5prime', overhangLength: 2, prototype: "HpaII", methylation: "1(5)" },
  "MspJI": { name: "MspJI", pattern: "CNNR", cutBefore: 13, cutBottom: 17, overhang: "", overhangType: '5prime', overhangLength: 4, typeIIS: true },
  "MspR9I": { name: "MspR9I", pattern: "CCNGG", cutBefore: 2, cutBottom: 3, overhang: "", overhangType: '5prime', overhangLength: 1, prototype: "ScrFI" },
  "MssI": { name: "MssI", pattern: "GTTTAAAC", cutBefore: 4, cutBottom: 4, overhang: "", overhangType: 'blunt', overhangLength: 0, prototype: "PmeI" },
  "MteI": { name: "MteI", pattern: "GCGCNGCGC", cutBefore: 4, cutBottom: 5, overhang: "", overhangType: '5prime', overhangLength: 1 },
  "MunI": { name: "MunI", pattern: "CAATTG", cutBefore: 1, cutBottom: 5, overhang: "AATT", overhangType: '5prime', overhangLength: 4, prototype: "MfeI", methylation: "3(6)" },
  "Mva1269I": { name: "Mva1269I", pattern: "GAATGC", cutBefore: 7, cutBottom: 5, overhang: "", overhangType: '3prime', overhangLength: 2, typeIIS: true, prototype: "BsmI" },
  "MvaI": { name: "MvaI", pattern: "CCWGG", cutBefore: 2, cutBottom: 3, overhang: "", overhangType: '5prime', overhangLength: 1, prototype: "EcoRII", methylation: "2(4)" },
  "MwoI": { name: "MwoI", pattern: "GCNNNNNNNGC", cutBefore: 7, cutBottom: 4, overhang: "", overhangType: '3prime', overhangLength: 3, methylation: "2(4)" },
  "NaeI": { name: "NaeI", pattern: "GCCGGC", cutBefore: 3, cutBottom: 3, overhang: "", overhangType: 'blunt', overhangLength: 0, methylation: "?(5)" },
  "NarI": { name: "NarI", pattern: "GGCGCC", cutBefore: 2, cutBottom: 4, overhang: "CG", overhangType: '5prime', overhangLength: 2 },
  "NciI": { name: "NciI", pattern: "CCSGG", cutBefore: 2, cutBottom: 3, overhang: "", overhangType: '5prime', overhangLength: 1, prototype: "CauII", methylation: "2(4)" },
  "NcoI": { name: "NcoI", pattern: "CCATGG", cutBefore: 1, cutBottom: 5, overhang: "CATG", overhangType: '5prime', overhangLength: 4, methylation: "?(4)" },
  "NdeI": { name: "NdeI", pattern: "CATATG", cutBefore: 2, cutBottom: 4, overhang: "TA", overhangType: '5prime', overhangLength: 2, methylation: "4(6)" },
  "NdeII": { name: "NdeII", pattern: "GATC", cutBefore: 0, cutBottom: 4, overhang: "GATC", overhangType: '5prime', overhangLength: 4, prototype: "MboI" },
  "NgoMIV": { name: "NgoMIV", pattern: "GCCGGC", cutBefore: 1, cutBottom: 5, overhang: "CCGG", overhangType: '5prime', overhangLength: 4, prototype: "NaeI", methylation: "2(5)" },
  "NheI": { name: "NheI", pattern: "GCTAGC", cutBefore: 1, cutBottom: 5, overhang: "CTAG", overhangType: '5prime', overhangLength: 4, methylation: "6(4)" },
  "NlaIII": { name: "NlaIII", pattern: "CATG", cutBefore: 4, cutBottom: 0, overhang: "CATG", overhangType: '3prime', overhangLength: 4, methylation: "2(6)" },
  "NlaIV": { name: "NlaIV", pattern: "GGNNCC", cutBefore: 3, cutBottom: 3, overhang: "", overhangType: 'blunt', overhangLength: 0, methylation: "?(5)" },
  "NmeAIII": { name: "NmeAIII", pattern: "GCCGAG", cutBefore: 27, cutBottom: 25, overhang: "", overhangType: '3prime', overhangLength: 2, typeIIS: true, methylation: "5(6)" },
  "NmuCI": { name: "NmuCI", pattern: "GTSAC", cutBefore: 0, cutBottom: 5, overhang: "", overhangType: '5prime', overhangLength: 5, prototype: "Tsp45I" },
  "NotI": { name: "NotI", pattern: "GCGGCCGC", cutBefore: 2, cutBottom: 6, overhang: "GGCC", overhangType: '5prime', overhangLength: 4, methylation: "2(4)" },
  "NruI": { name: "NruI", pattern: "TCGCGA", cutBefore: 3, cutBottom: 3, overhang: "", overhangType: 'blunt', overhangLength: 0, methylation: "2(4)" },
  "NsbI": { name: "NsbI", pattern: "TGCGCA", cutBefore: 3, cutBottom: 3, overhang: "", overhangType: 'blunt', overhangLength: 0, prototype: "MstI" },
  "NsiI": { name: "NsiI", pattern: "ATGCAT", cutBefore: 5, cutBottom: 1, overhang: "TGCA", overhangType: '3prime', overhangLength: 4, prototype: "AvaIII", methylation: "5(6)" },
  "NspI": { name: "NspI", pattern: "RCATGY", cutBefore: 5, cutBottom: 1, overhang: "CATG", overhangType: '3prime', overhangLength: 4, methylation: "2(5)" },
  "NspV": { name: "NspV", pattern: "TTCGAA", cutBefore: 2, cutBottom: 4, overhang: "CG", overhangType: '5prime', overhangLength: 2, prototype: "AsuII" },
  "OliI": { name: "OliI", pattern: "CACNNNNGTG", cutBefore: 5, cutBottom: 5, overhang: "", overhangType: 'blunt', overhangLength: 0 },
  "PacI": { name: "PacI", pattern: "TTAATTAA", cutBefore: 5, cutBottom: 3, overhang: "AT", overhangType: '3prime', overhangLength: 2 },
  "PaeI": { name: "PaeI", pattern: "GCATGC", cutBefore: 5, cutBottom: 1, overhang: "CATG", overhangType: '3prime', overhangLength: 4, prototype: "SphI" },
  "PaeR7I": { name: "PaeR7I", pattern: "CTCGAG", cutBefore: 1, cutBottom: 5, overhang: "TCGA", overhangType: '5prime', overhangLength: 4, prototype: "XhoI", methylation: "5(6)" },
  "PagI": { name: "PagI", pattern: "TCATGA", cutBefore: 1, cutBottom: 5, overhang: "CATG", overhangType: '5prime', overhangLength: 4, prototype: "BspHI" },
  "PalAI": { name: "PalAI", pattern: "GGCGCGCC", cutBefore: 2, cutBottom: 6, overhang: "CGCG", overhangType: '5prime', overhangLength: 4, prototype: "AscI" },
  "PaqCI": { name: "PaqCI", pattern: "CACCTGC", cutBefore: 11, cutBottom: 15, overhang: "", overhangType: '5prime', overhangLength: 4, typeIIS: true, prototype: "AarI", methylation: "?(5)" },
  "PasI": { name: "PasI", pattern: "CCCWGGG", cutBefore: 2, cutBottom: 5, overhang: "", overhangType: '5prime', overhangLength: 3 },
  "PauI": { name: "PauI", pattern: "GCGCGC", cutBefore: 1, cutBottom: 5, overhang: "CGCG", overhangType: '5prime', overhangLength: 4, prototype: "BsePI" },
  "PceI": { name: "PceI", pattern: "AGGCCT", cutBefore: 3, cutBottom: 3, overhang: "", overhangType: 'blunt', overhangLength: 0, prototype: "StuI" },
  "PciI": { name: "PciI", pattern: "ACATGT", cutBefore: 1, cutBottom: 5, overhang: "CATG", overhangType: '5prime', overhangLength: 4, prototype: "BspLU11I" },
  "PciSI": { name: "PciSI", pattern: "GCTCTTC", cutBefore: 8, cutBottom: 11, overhang: "", overhangType: '5prime', overhangLength: 3, typeIIS: true, prototype: "SapI" },
  "PcsI": { name: "PcsI", pattern: "WCGNNNNNNNCGW", cutBefore: 7, cutBottom: 6, overhang: "", overhangType: '3prime', overhangLength: 1 },
  "PctI": { name: "PctI", pattern: "GAATGC", cutBefore: 7, cutBottom: 5, overhang: "", overhangType: '3prime', overhangLength: 2, typeIIS: true, prototype: "BsmI" },
  "PdiI": { name: "PdiI", pattern: "GCCGGC", cutBefore: 3, cutBottom: 3, overhang: "", overhangType: 'blunt', overhangLength: 0, prototype: "NaeI" },
  "PdmI": { name: "PdmI", pattern: "GAANNNNTTC", cutBefore: 5, cutBottom: 5, overhang: "", overhangType: 'blunt', overhangLength: 0, prototype: "XmnI" },
  "PecI": { name: "PecI", pattern: "TTATAA", cutBefore: 3, cutBottom: 3, overhang: "", overhangType: 'blunt', overhangLength: 0, prototype: "PsiI" },
  "PfeI": { name: "PfeI", pattern: "GAWTC", cutBefore: 1, cutBottom: 4, overhang: "", overhangType: '5prime', overhangLength: 3, prototype: "TfiI" },
  "Pfl23II": { name: "Pfl23II", pattern: "CGTACG", cutBefore: 1, cutBottom: 5, overhang: "GTAC", overhangType: '5prime', overhangLength: 4, prototype: "SplI" },
  "PflFI": { name: "PflFI", pattern: "GACNNNGTC", cutBefore: 4, cutBottom: 5, overhang: "", overhangType: '5prime', overhangLength: 1, prototype: "Tth111I" },
  "PflMI": { name: "PflMI", pattern: "CCANNNNNTGG", cutBefore: 7, cutBottom: 4, overhang: "", overhangType: '3prime', overhangLength: 3, methylation: "3(6)" },
  "PfoI": { name: "PfoI", pattern: "TCCNGGA", cutBefore: 1, cutBottom: 6, overhang: "", overhangType: '5prime', overhangLength: 5 },
  "PinAI": { name: "PinAI", pattern: "ACCGGT", cutBefore: 1, cutBottom: 5, overhang: "CCGG", overhangType: '5prime', overhangLength: 4, prototype: "AgeI" },
  "PkrI": { name: "PkrI", pattern: "GCNGC", cutBefore: 3, cutBottom: 2, overhang: "", overhangType: '3prime', overhangLength: 1, prototype: "BisI" },
  "Ple19I": { name: "Ple19I", pattern: "CGATCG", cutBefore: 4, cutBottom: 2, overhang: "AT", overhangType: '3prime', overhangLength: 2, prototype: "PvuI" },
  "PleI": { name: "PleI", pattern: "GAGTC", cutBefore: 9, cutBottom: 10, overhang: "", overhangType: '5prime', overhangLength: 1, typeIIS: true, methylation: "2(6)" },
  "PluTI": { name: "PluTI", pattern: "GGCGCC", cutBefore: 5, cutBottom: 1, overhang: "GCGC", overhangType: '3prime', overhangLength: 4, prototype: "NarI", methylation: "3(5)" },
  "PmeI": { name: "PmeI", pattern: "GTTTAAAC", cutBefore: 4, cutBottom: 4, overhang: "", overhangType: 'blunt', overhangLength: 0 },
  "PmlI": { name: "PmlI", pattern: "CACGTG", cutBefore: 3, cutBottom: 3, overhang: "", overhangType: 'blunt', overhangLength: 0, prototype: "PmaCI", methylation: "3(5)" },
  "PpsI": { name: "PpsI", pattern: "GAGTC", cutBefore: 9, cutBottom: 10, overhang: "", overhangType: '5prime', overhangLength: 1, typeIIS: true, prototype: "PleI" },
  "Ppu21I": { name: "Ppu21I", pattern: "YACGTR", cutBefore: 3, cutBottom: 3, overhang: "", overhangType: 'blunt', overhangLength: 0, prototype: "BsaAI" },
  "PpuMI": { name: "PpuMI", pattern: "RGGWCCY", cutBefore: 2, cutBottom: 5, overhang: "", overhangType: '5prime', overhangLength: 3, methylation: "?(5)" },
  "PscI": { name: "PscI", pattern: "ACATGT", cutBefore: 1, cutBottom: 5, overhang: "CATG", overhangType: '5prime', overhangLength: 4, prototype: "BspLU11I" },
  "Pse31I": { name: "Pse31I", pattern: "GGTCTC", cutBefore: 7, cutBottom: 11, overhang: "", overhangType: '5prime', overhangLength: 4, typeIIS: true, prototype: "Eco31I" },
  "PshAI": { name: "PshAI", pattern: "GACNNNNGTC", cutBefore: 5, cutBottom: 5, overhang: "", overhangType: 'blunt', overhangLength: 0, methylation: "2(6)" },
  "PsiI": { name: "PsiI", pattern: "TTATAA", cutBefore: 3, cutBottom: 3, overhang: "", overhangType: 'blunt', overhangLength: 0, methylation: "6(6)" },
  "Psp124BI": { name: "Psp124BI", pattern: "GAGCTC", cutBefore: 5, cutBottom: 1, overhang: "AGCT", overhangType: '3prime', overhangLength: 4, prototype: "SacI" },
  "Psp1406I": { name: "Psp1406I", pattern: "AACGTT", cutBefore: 2, cutBottom: 4, overhang: "CG", overhangType: '5prime', overhangLength: 2, prototype: "AclI" },
  "Psp5II": { name: "Psp5II", pattern: "RGGWCCY", cutBefore: 2, cutBottom: 5, overhang: "", overhangType: '5prime', overhangLength: 3, prototype: "PpuMI" },
  "Psp6I": { name: "Psp6I", pattern: "CCWGG", cutBefore: 0, cutBottom: 5, overhang: "", overhangType: '5prime', overhangLength: 5, prototype: "EcoRII" },
  "PspCI": { name: "PspCI", pattern: "CACGTG", cutBefore: 3, cutBottom: 3, overhang: "", overhangType: 'blunt', overhangLength: 0, prototype: "PmaCI" },
  "PspEI": { name: "PspEI", pattern: "GGTNACC", cutBefore: 1, cutBottom: 6, overhang: "", overhangType: '5prime', overhangLength: 5, prototype: "BstEII" },
  "PspGI": { name: "PspGI", pattern: "CCWGG", cutBefore: 0, cutBottom: 5, overhang: "", overhangType: '5prime', overhangLength: 5, prototype: "EcoRII", methylation: "?(4)" },
  "PspLI": { name: "PspLI", pattern: "CGTACG", cutBefore: 1, cutBottom: 5, overhang: "GTAC", overhangType: '5prime', overhangLength: 4, prototype: "SplI" },
  "PspN4I": { name: "PspN4I", pattern: "GGNNCC", cutBefore: 3, cutBottom: 3, overhang: "", overhangType: 'blunt', overhangLength: 0, prototype: "NlaIV" },
  "PspOMI": { name: "PspOMI", pattern: "GGGCCC", cutBefore: 1, cutBottom: 5, overhang: "GGCC", overhangType: '5prime', overhangLength: 4, prototype: "ApaI", methylation: "5(4)" },
  "PspPPI": { name: "PspPPI", pattern: "RGGWCCY", cutBefore: 2, cutBottom: 5, overhang: "", overhangType: '5prime', overhangLength: 3, prototype: "PpuMI" },
  "PspXI": { name: "PspXI", pattern: "VCTCGAGB", cutBefore: 2, cutBottom: 6, overhang: "TCGA", overhangType: '5prime', overhangLength: 4 },
  "PstI": { name: "PstI", pattern: "CTGCAG", cutBefore: 5, cutBottom: 1, overhang: "TGCA", overhangType: '3prime', overhangLength: 4, methylation: "5(6)" },
  "PstNI": { name: "PstNI", pattern: "CAGNNNCTG", cutBefore: 6, cutBottom: 3, overhang: "", overhangType: '3prime', overhangLength: 3, prototype: "AlwNI" },
  "PsuI": { name: "PsuI", pattern: "RGATCY", cutBefore: 1, cutBottom: 5, overhang: "GATC", overhangType: '5prime', overhangLength: 4, prototype: "XhoII" },
  "PsyI": { name: "PsyI", pattern: "GACNNNGTC", cutBefore: 4, cutBottom: 5, overhang: "", overhangType: '5prime', overhangLength: 1, prototype: "Tth111I" },
  "PvuI": { name: "PvuI", pattern: "CGATCG", cutBefore: 4, cutBottom: 2, overhang: "AT", overhangType: '3prime', overhangLength: 2 },
  "PvuII": { name: "PvuII", pattern: "CAGCTG", cutBefore: 3, cutBottom: 3, overhang: "", overhangType: 'blunt', overhangLength: 0, methylation: "4(4)" },
  "RgaI": { name: "RgaI", pattern: "GCGATCGC", cutBefore: 5, cutBottom: 3, overhang: "AT", overhangType: '3prime', overhangLength: 2, prototype: "SgfI" },
  "RigI": { name: "RigI", pattern: "GGCCGGCC", cutBefore: 6, cutBottom: 2, overhang: "CCGG", overhangType: '3prime', overhangLength: 4, prototype: "FseI" },
  "RsaI": { name: "RsaI", pattern: "GTAC", cutBefore: 2, cutBottom: 2, overhang: "", overhangType: 'blunt', overhangLength: 0, methylation: "4(4)" },
  "RsaNI": { name: "RsaNI", pattern: "GTAC", cutBefore: 1, cutBottom: 3, overhang: "TA", overhangType: '5prime', overhangLength: 2, prototype: "RsaI" },
  "RseI": { name: "RseI", pattern: "CAYNNNNRTG", cutBefore: 5, cutBottom: 5, overhang: "", overhangType: 'blunt', overhangLength: 0, prototype: "MslI" },
  "Rsr2I": { name: "Rsr2I", pattern: "CGGWCCG", cutBefore: 2, cutBottom: 5, overhang: "", overhangType: '5prime', overhangLength: 3, prototype: "RsrII" },
  "RsrII": { name: "RsrII", pattern: "CGGWCCG", cutBefore: 2, cutBottom: 5, overhang: "", overhangType: '5prime', overhangLength: 3, methylation: "?(5)" },
  "SacI": { name: "SacI", pattern: "GAGCTC", cutBefore: 5, cutBottom: 1, overhang: "AGCT", overhangType: '3prime', overhangLength: 4, methylation: "4(5)" },
  "SacII": { name: "SacII", pattern: "CCGCGG", cutBefore: 4, cutBottom: 2, overhang: "GC", overhangType: '3prime', overhangLength: 2, methylation: "2(5)" },
  "SalI": { name: "SalI", pattern: "GTCGAC", cutBefore: 1, cutBottom: 5, overhang: "TCGA", overhangType: '5prime', overhangLength: 4, methylation: "5(6)" },
  "SapI": { name: "SapI", pattern: "GCTCTTC", cutBefore: 8, cutBottom: 11, overhang: "", overhangType: '5prime', overhangLength: 3, typeIIS: true, methylation: "2(4),-5(6)" },
  "SatI": { name: "SatI", pattern: "GCNGC", cutBefore: 2, cutBottom: 3, overhang: "", overhangType: '5prime', overhangLength: 1, prototype: "Fnu4HI" },
  "Sau3AI": { name: "Sau3AI", pattern: "GATC", cutBefore: 0, cutBottom: 4, overhang: "GATC", overhangType: '5prime', overhangLength: 4, prototype: "MboI", methylation: "4(5)" },
  "Sau96I": { name: "Sau96I", pattern: "GGNCC", cutBefore: 1, cutBottom: 4, overhang: "", overhangType: '5prime', overhangLength: 3, prototype: "AsuI", methylation: "4(5)" },
  "SbfI": { name: "SbfI", pattern: "CCTGCAGG", cutBefore: 6, cutBottom: 2, overhang: "TGCA", overhangType: '3prime', overhangLength: 4, prototype: "Sse8387I", methylation: "6(6)" },
  "ScaI": { name: "ScaI", pattern: "AGTACT", cutBefore: 3, cutBottom: 3, overhang: "", overhangType: 'blunt', overhangLength: 0, methylation: "5(4)" },
  "SchI": { name: "SchI", pattern: "GAGTC", cutBefore: 10, cutBottom: 10, overhang: "", overhangType: 'blunt', overhangLength: 0, typeIIS: true, prototype: "PleI" },
  "ScrFI": { name: "ScrFI", pattern: "CCNGG", cutBefore: 2, cutBottom: 3, overhang: "", overhangType: '5prime', overhangLength: 1, methylation: "2(5)" },
  "SdaI": { name: "SdaI", pattern: "CCTGCAGG", cutBefore: 6, cutBottom: 2, overhang: "TGCA", overhangType: '3prime', overhangLength: 4, prototype: "Sse8387I" },
  "SduI": { name: "SduI", pattern: "GDGCHC", cutBefore: 5, cutBottom: 1, overhang: "", overhangType: '3prime', overhangLength: 4 },
  "SetI": { name: "SetI", pattern: "ASST", cutBefore: 4, cutBottom: 0, overhang: "", overhangType: '3prime', overhangLength: 4 },
  "SexAI": { name: "SexAI", pattern: "ACCWGGT", cutBefore: 1, cutBottom: 6, overhang: "", overhangType: '5prime', overhangLength: 5, methylation: "2(5)" },
  "SfaAI": { name: "SfaAI", pattern: "GCGATCGC", cutBefore: 5, cutBottom: 3, overhang: "AT", overhangType: '3prime', overhangLength: 2, prototype: "SgfI" },
  "SfaNI": { name: "SfaNI", pattern: "GCATC", cutBefore: 10, cutBottom: 14, overhang: "", overhangType: '5prime', overhangLength: 4, typeIIS: true },
  "SfcI": { name: "SfcI", pattern: "CTRYAG", cutBefore: 1, cutBottom: 5, overhang: "", overhangType: '5prime', overhangLength: 4, prototype: "SfeI" },
  "SfiI": { name: "SfiI", pattern: "GGCCNNNNNGGCC", cutBefore: 8, cutBottom: 5, overhang: "", overhangType: '3prime', overhangLength: 3, methylation: "3(4)" },
  "SfoI": { name: "SfoI", pattern: "GGCGCC", cutBefore: 3, cutBottom: 3, overhang: "", overhangType: 'blunt', overhangLength: 0, prototype: "NarI", methylation: "?(5)" },
  "Sfr274I": { name: "Sfr274I", pattern: "CTCGAG", cutBefore: 1, cutBottom: 5, overhang: "TCGA", overhangType: '5prime', overhangLength: 4, prototype: "XhoI" },
  "Sfr303I": { name: "Sfr303I", pattern: "CCGCGG", cutBefore: 4, cutBottom: 2, overhang: "GC", overhangType: '3prime', overhangLength: 2, prototype: "SacII" },
  "SfuI": { name: "SfuI", pattern: "TTCGAA", cutBefore: 2, cutBottom: 4, overhang: "CG", overhangType: '5prime', overhangLength: 2, prototype: "AsuII" },
  "SgeI": { name: "SgeI", pattern: "CNNGNNNNNNNNN", cutBefore: 13, cutBottom: 0, overhang: "", overhangType: '3prime', overhangLength: 13 },
  "SgfI": { name: "SgfI", pattern: "GCGATCGC", cutBefore: 5, cutBottom: 3, overhang: "AT", overhangType: '3prime', overhangLength: 2 },
  "SgrAI": { name: "SgrAI", pattern: "CRCCGGYG", cutBefore: 2, cutBottom: 6, overhang: "CCGG", overhangType: '5prime', overhangLength: 4, methylation: "3(5)" },
  "SgrDI": { name: "SgrDI", pattern: "CGTCGACG", cutBefore: 2, cutBottom: 6, overhang: "TCGA", overhangType: '5prime', overhangLength: 4 },
  "SgsI": { name: "SgsI", pattern: "GGCGCGCC", cutBefore: 2, cutBottom: 6, overhang: "CGCG", overhangType: '5prime', overhangLength: 4, prototype: "AscI" },
  "SinI": { name: "SinI", pattern: "GGWCC", cutBefore: 1, cutBottom: 4, overhang: "", overhangType: '5prime', overhangLength: 3, prototype: "AvaII", methylation: "4(5)" },
  "SmaI": { name: "SmaI", pattern: "CCCGGG", cutBefore: 3, cutBottom: 3, overhang: "", overhangType: 'blunt', overhangLength: 0, methylation: "2(4)" },
  "SmiI": { name: "SmiI", pattern: "ATTTAAAT", cutBefore: 4, cutBottom: 4, overhang: "", overhangType: 'blunt', overhangLength: 0, prototype: "SwaI" },
  "SmiMI": { name: "SmiMI", pattern: "CAYNNNNRTG", cutBefore: 5, cutBottom: 5, overhang: "", overhangType: 'blunt', overhangLength: 0, prototype: "MslI" },
  "SmlI": { name: "SmlI", pattern: "CTYRAG", cutBefore: 1, cutBottom: 5, overhang: "", overhangType: '5prime', overhangLength: 4, methylation: "5(6)" },
  "SmoI": { name: "SmoI", pattern: "CTYRAG", cutBefore: 1, cutBottom: 5, overhang: "", overhangType: '5prime', overhangLength: 4, prototype: "SmlI" },
  "SnaBI": { name: "SnaBI", pattern: "TACGTA", cutBefore: 3, cutBottom: 3, overhang: "", overhangType: 'blunt', overhangLength: 0, methylation: "3(4)" },
  "SpeI": { name: "SpeI", pattern: "ACTAGT", cutBefore: 1, cutBottom: 5, overhang: "CTAG", overhangType: '5prime', overhangLength: 4, methylation: "1(6)" },
  "SphI": { name: "SphI", pattern: "GCATGC", cutBefore: 5, cutBottom: 1, overhang: "CATG", overhangType: '3prime', overhangLength: 4 },
  "SrfI": { name: "SrfI", pattern: "GCCCGGGC", cutBefore: 4, cutBottom: 4, overhang: "", overhangType: 'blunt', overhangLength: 0 },
  "Sse9I": { name: "Sse9I", pattern: "AATT", cutBefore: 0, cutBottom: 4, overhang: "AATT", overhangType: '5prime', overhangLength: 4, prototype: "TspEI", methylation: "2(6)" },
  "SsiI": { name: "SsiI", pattern: "CCGC", cutBefore: 1, cutBottom: 3, overhang: "", overhangType: '5prime', overhangLength: 2, typeIIS: true, prototype: "AciI" },
  "SspDI": { name: "SspDI", pattern: "GGCGCC", cutBefore: 1, cutBottom: 5, overhang: "GCGC", overhangType: '5prime', overhangLength: 4, prototype: "NarI" },
  "SspI": { name: "SspI", pattern: "AATATT", cutBefore: 3, cutBottom: 3, overhang: "", overhangType: 'blunt', overhangLength: 0, methylation: "?(6)" },
  "SspMI": { name: "SspMI", pattern: "CTAG", cutBefore: 1, cutBottom: 3, overhang: "TA", overhangType: '5prime', overhangLength: 2, prototype: "MaeI" },
  "StuI": { name: "StuI", pattern: "AGGCCT", cutBefore: 3, cutBottom: 3, overhang: "", overhangType: 'blunt', overhangLength: 0 },
  "StyD4I": { name: "StyD4I", pattern: "CCNGG", cutBefore: 0, cutBottom: 5, overhang: "", overhangType: '5prime', overhangLength: 5, prototype: "ScrFI", methylation: "?(5)" },
  "StyI": { name: "StyI", pattern: "CCWWGG", cutBefore: 1, cutBottom: 5, overhang: "", overhangType: '5prime', overhangLength: 4, methylation: "?(4)" },
  "SwaI": { name: "SwaI", pattern: "ATTTAAAT", cutBefore: 4, cutBottom: 4, overhang: "", overhangType: 'blunt', overhangLength: 0, methylation: "?(6)" },
  "TaaI": { name: "TaaI", pattern: "ACNGT", cutBefore: 3, cutBottom: 2, overhang: "", overhangType: '3prime', overhangLength: 1, prototype: "Tsp4CI" },
  "TaiI": { name: "TaiI", pattern: "ACGT", cutBefore: 4, cutBottom: 0, overhang: "ACGT", overhangType: '3prime', overhangLength: 4, prototype: "MaeII" },
  "TaqI": { name: "TaqI", pattern: "TCGA", cutBefore: 1, cutBottom: 3, overhang: "CG", overhangType: '5prime', overhangLength: 2, methylation: "4(6)" },
  "TaqII": { name: "TaqII", pattern: "GACCGA", cutBefore: 17, cutBottom: 15, overhang: "", overhangType: '3prime', overhangLength: 2, typeIIS: true, methylation: "6(6)" },
  "TasI": { name: "TasI", pattern: "AATT", cutBefore: 0, cutBottom: 4, overhang: "AATT", overhangType: '5prime', overhangLength: 4, prototype: "TspEI" },
  "TatI": { name: "TatI", pattern: "WGTACW", cutBefore: 1, cutBottom: 5, overhang: "GTAC", overhangType: '5prime', overhangLength: 4 },
  "TauI": { name: "TauI", pattern: "GCSGC", cutBefore: 4, cutBottom: 1, overhang: "", overhangType: '3prime', overhangLength: 3 },
  "TfiI": { name: "TfiI", pattern: "GAWTC", cutBefore: 1, cutBottom: 4, overhang: "", overhangType: '5prime', overhangLength: 3, methylation: "2(6)" },
  "Tru1I": { name: "Tru1I", pattern: "TTAA", cutBefore: 1, cutBottom: 3, overhang: "TA", overhangType: '5prime', overhangLength: 2, prototype: "MseI" },
  "Tru9I": { name: "Tru9I", pattern: "TTAA", cutBefore: 1, cutBottom: 3, overhang: "TA", overhangType: '5prime', overhangLength: 2, prototype: "MseI" },
  "TscAI": { name: "TscAI", pattern: "CASTGNN", cutBefore: 7, cutBottom: 0, overhang: "", overhangType: '3prime', overhangLength: 7, prototype: "TspRI" },
  "TseFI": { name: "TseFI", pattern: "GTSAC", cutBefore: 0, cutBottom: 5, overhang: "", overhangType: '5prime', overhangLength: 5, prototype: "Tsp45I" },
  "TseI": { name: "TseI", pattern: "GCWGC", cutBefore: 1, cutBottom: 4, overhang: "", overhangType: '5prime', overhangLength: 3, methylation: "2(5)" },
  "Tsp45I": { name: "Tsp45I", pattern: "GTSAC", cutBefore: 0, cutBottom: 5, overhang: "", overhangType: '5prime', overhangLength: 5, methylation: "4(6)" },
  "TspDTI": { name: "TspDTI", pattern: "ATGAA", cutBefore: 16, cutBottom: 14, overhang: "", overhangType: '3prime', overhangLength: 2, typeIIS: true },
  "TspGWI": { name: "TspGWI", pattern: "ACGGA", cutBefore: 16, cutBottom: 14, overhang: "", overhangType: '3prime', overhangLength: 2, typeIIS: true, methylation: "?(6)" },
  "TspMI": { name: "TspMI", pattern: "CCCGGG", cutBefore: 1, cutBottom: 5, overhang: "CCGG", overhangType: '5prime', overhangLength: 4, prototype: "SmaI", methylation: "?(5)" },
  "TspRI": { name: "TspRI", pattern: "CASTGNN", cutBefore: 7, cutBottom: 0, overhang: "", overhangType: '3prime', overhangLength: 7, methylation: "1(5)" },
  "Tth111I": { name: "Tth111I", pattern: "GACNNNGTC", cutBefore: 4, cutBottom: 5, overhang: "", overhangType: '5prime', overhangLength: 1, methylation: "2(6)" },
  "Van91I": { name: "Van91I", pattern: "CCANNNNNTGG", cutBefore: 7, cutBottom: 4, overhang: "", overhangType: '3prime', overhangLength: 3, prototype: "PflMI" },
  "Vha464I": { name: "Vha464I", pattern: "CTTAAG", cutBefore: 1, cutBottom: 5, overhang: "TTAA", overhangType: '5prime', overhangLength: 4, prototype: "AflII" },
  "VneI": { name: "VneI", pattern: "GTGCAC", cutBefore: 1, cutBottom: 5, overhang: "TGCA", overhangType: '5prime', overhangLength: 4, prototype: "ApaLI" },
  "VspI": { name: "VspI", pattern: "ATTAAT", cutBefore: 2, cutBottom: 4, overhang: "TA", overhangType: '5prime', overhangLength: 2, methylation: "5(6)" },
  "XagI": { name: "XagI", pattern: "CCTNNNNNAGG", cutBefore: 5, cutBottom: 6, overhang: "", overhangType: '5prime', overhangLength: 1, prototype: "EcoNI" },
  "XapI": { name: "XapI", pattern: "RAATTY", cutBefore: 1, cutBottom: 5, overhang: "AATT", overhangType: '5prime', overhangLength: 4, prototype: "ApoI" },
  "XbaI": { name: "XbaI", pattern: "TCTAGA", cutBefore: 1, cutBottom: 5, overhang: "CTAG", overhangType: '5prime', overhangLength: 4, methylation: "6(6)" },
  "XceI": { name: "XceI", pattern: "RCATGY", cutBefore: 5, cutBottom: 1, overhang: "CATG", overhangType: '3prime', overhangLength: 4, prototype: "NspI" },
  "XcmI": { name: "XcmI", pattern: "CCANNNNNNNNNTGG", cutBefore: 8, cutBottom: 7, overhang: "", overhangType: '3prime', overhangLength: 1, methylation: "3(6)" },
  "XhoI": { name: "XhoI", pattern: "CTCGAG", cutBefore: 1, cutBottom: 5, overhang: "TCGA", overhangType: '5prime', overhangLength: 4, methylation: "5(6)" },
  "XhoII": { name: "XhoII", pattern: "RGATCY", cutBefore: 1, cutBottom: 5, overhang: "GATC", overhangType: '5prime', overhangLength: 4, methylation: "5(4)" },
  "XmaCI": { name: "XmaCI", pattern: "CCCGGG", cutBefore: 1, cutBottom: 5, overhang: "CCGG", overhangType: '5prime', overhangLength: 4, prototype: "SmaI" },
  "XmaI": { name: "XmaI", pattern: "CCCGGG", cutBefore: 1, cutBottom: 5, overhang: "CCGG", overhangType: '5prime', overhangLength: 4, prototype: "SmaI", methylation: "2(4)" },
  "XmaJI": { name: "XmaJI", pattern: "CCTAGG", cutBefore: 1, cutBottom: 5, overhang: "CTAG", overhangType: '5prime', overhangLength: 4, prototype: "AvrII" },
  "XmiI": { name: "XmiI", pattern: "GTMKAC", cutBefore: 2, cutBottom: 4, overhang: "", overhangType: '5prime', overhangLength: 2, prototype: "AccI" },
  "XmnI": { name: "XmnI", pattern: "GAANNNNTTC", cutBefore: 5, cutBottom: 5, overhang: "", overhangType: 'blunt', overhangLength: 0, methylation: "2(6)" },
  "ZraI": { name: "ZraI", pattern: "GACGTC", cutBefore: 3, cutBottom: 3, overhang: "", overhangType: 'blunt', overhangLength: 0, prototype: "AatII" },
  "ZrmI": { name: "ZrmI", pattern: "AGTACT", cutBefore: 3, cutBottom: 3, overhang: "", overhangType: 'blunt', overhangLength: 0, prototype: "ScaI" },
  "Zsp2I": { name: "Zsp2I", pattern: "ATGCAT", cutBefore: 5, cutBottom: 1, overhang: "TGCA", overhangType: '3prime', overhangLength: 4, prototype: "AvaIII" },
};
